export const optionValues = {
  optionsArea: {
    _selfKey: 'optionsArea',
    animate: true,
    boxShadow: true,
    fillColor: 'blue',
    gradient: false,
    gradientAxis: 'y',
    gradientColor: ['red', 'yellow'],
    height: 500,
    hoverColor: 'blue',
    isUpdating: false,
    margin: {
      top: 20,
      bottom: 30,
      left: 40,
      right: 20,
    },
    onHover: true,
    opacity: 0.61,
    sortBy: 'y asc',
    // stack: false,
    textAnchor: 'middle',
    width: 960,
    xDomain: null,
    xLabel: 'xLabel',
    xLabelFontColor: 'black',
    xLabelFontFamily: 'Arial, sans-serif',
    xLabelFontSize: 12,
    xLabelFontOpacity: 1,
    xLabelFontWeight: 'bold',
    xLabelOffsetX: 0,
    xLabelOffsetY: 10,
    xLabelRotation: 90,
    xLine: false,
    xTickExtension: 0,
    xTickFontColor: '#333',
    xTickFontFamily: 'sans-serif',
    xTickFontOpacity: 1,
    xTickFontWeight: 'normal',
    xTickFontSize: 10,
    xTickFrequency: 10,
    xTickLength: 10,
    xTickOpacity: 1,
    xAxisColor: 'red',
    xAxisPosition: -1,
    yDomain: null,
    yLabel: 'yLabel',
    yLabelFontColor: 'black',
    yLabelFontFamily: 'Arial, sans-serif',
    yLabelFontSize: 12,
    yLabelFontOpacity: 1,
    yLabelFontWeight: 'bold',
    yLabelOffsetX: 0,
    yLabelOffsetY: 50,
    yLabelRotation: 0,
    yLine: false,
    yTickExtension: 100,
    yTickFontColor: '#333',
    yTickFontFamily: 'sans-serif',
    yTickFontOpacity: 0.55,
    yTickFontWeight: 'normal',
    yTickFontSize: 10,
    yTickFrequency: 10,
    yTickLength: 10,
    yAxisColor: 'blue',
    yAxisPosition: 880,
  },
  optionsBar: {
    _selfKey: 'optionsBar',
    // animate: true,
    barWidth: 0,
    boxShadow: true,
    fillColor: 'green',
    gradient: false,
    gradientAxis: 'y',
    gradientColor: ['blue', 'red'],
    height: 500,
    hoverColor: 'blue',
    // isUpdating: false,
    margin: {
      top: 20,
      bottom: 30,
      left: 40,
      right: 20,
    },
    onHover: true,
    opacity: 0.61,
    sortBy: 'y asc',
    // stack: false,
    textAnchor: 'middle',
    width: 960,
    xDomain: null,
    xLabel: 'xLabel',
    xLabelFontColor: 'black',
    xLabelFontFamily: 'Arial, sans-serif',
    xLabelFontSize: 12,
    xLabelFontOpacity: 1,
    xLabelFontWeight: 'bold',
    xLabelOffsetX: 0,
    xLabelOffsetY: 10,
    xLabelRotation: 90,
    xLine: false,
    xTickExtension: 0,
    xTickFontColor: '#333',
    xTickFontFamily: 'sans-serif',
    xTickFontOpacity: 1,
    xTickFontWeight: 'normal',
    xTickFontSize: 10,
    xTickFrequency: 10,
    xTickLength: 10,
    xTickOpacity: 1,
    xAxisColor: 'red',
    xAxisPosition: -1,
    yDomain: null,
    yLabel: 'yLabel',
    yLabelFontColor: 'black',
    yLabelFontFamily: 'Arial, sans-serif',
    yLabelFontSize: 12,
    yLabelFontOpacity: 1,
    yLabelFontWeight: 'bold',
    yLabelOffsetX: 0,
    yLabelOffsetY: 50,
    yLabelRotation: 0,
    yLine: false,
    yTickExtension: 100,
    yTickFontColor: '#333',
    yTickFontFamily: 'sans-serif',
    yTickFontOpacity: 0.55,
    yTickFontWeight: 'normal',
    yTickFontSize: 10,
    yTickFrequency: 10,
    yTickLength: 10,
    yAxisColor: 'blue',
    yAxisPosition: 880,
  },
  optionsBox: {
    _selfKey: 'optionsBox',
    // animate: false,
    boxShadow: true,
    boxWidth: 10,
    fillColor: 'blue',
    gradient: false,
    gradientAxis: 'y',
    gradientColor: ['red', 'yellow'],
    height: 800,
    hoverColor: 'blue',
    isUpdating: false,
    margin: {
      top: 20,
      bottom: 30,
      left: 40,
      right: 20,
    },
    onHover: true,
    opacity: 0.61,
    sortBy: 'y asc',
    strokeColor: 'black',
    // stack: false,
    textAnchor: 'middle',
    width: 960,
    xDomain: null,
    xLabel: 'xLabel',
    xLabelFontColor: 'black',
    xLabelFontFamily: 'Arial, sans-serif',
    xLabelFontSize: 12,
    xLabelFontOpacity: 1,
    xLabelFontWeight: 'bold',
    xLabelOffsetX: 0,
    xLabelOffsetY: 10,
    xLabelRotation: 90,
    xLine: false,
    xTickExtension: 0,
    xTickFontColor: '#333',
    xTickFontFamily: 'sans-serif',
    xTickFontOpacity: 1,
    xTickFontWeight: 'normal',
    xTickFontSize: 10,
    xTickFrequency: 10,
    xTickLength: 10,
    xTickOpacity: 1,
    xAxisColor: 'red',
    xAxisPosition: -1,
    yDomain: null,
    yLabel: 'yLabel',
    yLabelFontColor: 'black',
    yLabelFontFamily: 'Arial, sans-serif',
    yLabelFontSize: 12,
    yLabelFontOpacity: 1,
    yLabelFontWeight: 'bold',
    yLabelOffsetX: 0,
    yLabelOffsetY: 50,
    yLabelRotation: 0,
    yLine: false,
    yTickExtension: 100,
    yTickFontColor: '#333',
    yTickFontFamily: 'sans-serif',
    yTickFontOpacity: 0.55,
    yTickFontWeight: 'normal',
    yTickFontSize: 10,
    yTickFrequency: 10,
    yTickLength: 10,
    yAxisColor: 'blue',
    yAxisPosition: 880,
  },
  optionsBubble: {
    _selfKey: 'optionsBubble',
    diameter: 1000, // The diameter of the bubble chart
    padding: 1.5, // The amount of padding between bubbles
    opacity: 0.8, // The opacity of the bubbles
    colorScheme: ['red', 'blue', 'purple', 'green'], // The color scheme for the bubbles
    label: 'Root Category',
    textAnchor: 'middle', // The position of the text within the bubbles
    parentTextSize: 20, // The font size of the text for parent nodes
    childTextSize: 14, // The font size of the text for child nodes
    fontColor: '#000', // The color of the text
    height: 1500, // The height of the chart
    width: 1200,
  },

  optionsChord: {
    _selfKey: 'optionsChord',
    colorScheme: ['red', 'blue', 'green'],
    childTextSize: 20,
    textAnchor: 'middle',
    height: 900,
    innerRadius: 200,
    margin: {
      bottom: 30,
      left: 30,
      right: 30,
      top: 30,
    },
    outerRadius: 200,
    strokeColor: 'red',
    width: 600,
  },

  optionsAdjacency: {
    _selfKey: 'optionsAdjacency',
    height: 500,
    minColor: 'blue',
    margin: {
      bottom: 20,
      left: 20,
      right: 20,
      top: 20,
    },
    maxColor: 'red',
    width: 700,
    xDomain: [0, 100],
    xLabel: 'X Axis',
    xLabelFontColor: 'green',
    xLabelFontFamily: 'Arial',
    xLabelFontSize: 14,
    xLabelFontOpacity: 1,
    xLabelFontWeight: 'normal',
    xLabelOffsetX: 10,
    xLabelOffsetY: -10,
    xLabelRotation: 0,
    xLine: true,
    xTickExtension: 5,
    xTickFontColor: '#000000',
    xTickFontFamily: 'Arial',
    xTickFontOpacity: 1,
    xTickFontWeight: 'normal',
    xTickFontSize: 12,
    xTickFrequency: 10,
    xTickLength: 5,
    xTickOpacity: 1,
    xAxisColor: '#000000',
    xAxisPosition: 490,
    yDomain: [0, 100],
    yLabel: 'Y Axis',
    yLabelFontColor: '#000000',
    yLabelFontFamily: 'Arial',
    yLabelFontSize: 14,
    yLabelFontOpacity: 1,
    yLabelFontWeight: 'normal',
    yLabelOffsetX: -10,
    yLabelOffsetY: 10,
    yLabelRotation: 0,
    yLine: true,
    yTickExtension: 5,
    yTickFontColor: '#000000',
    yTickFontFamily: 'Arial',
    yTickFontOpacity: 1,
    yTickFontWeight: 'normal',
    yTickFontSize: 12,
    yTickFrequency: 10,
    yTickLength: 5,
    yAxisColor: '#000000',
    yAxisPosition: 210,
  },
  optionsCloud: {
    _selfKey: 'optionsCloud',
    colorScheme: ['red', 'blue', 'green', 'yellow'],
    bubble: true,
    bubbleOpacity: 0.2,
    chargeStrength: -0.4,
    fontColor: 'black',
    height: 200,
    margin: {
      bottom: 50,
      left: 50,
      right: 50,
      top: 50,
    },
    maxRadius: 40,
    textAnchor: 'middle',
    width: 300,
    y2ForceStrength: 0.03,
  },
  optionsCluster: {
    _selfKey: 'optionsCluster',
    width: 800, // Width of the svg
    height: 600, // Height of the svg
    label: 'Root Category',
    margin: {
      top: 20, right: 120, bottom: 20, left: 120,
    },
    colorScheme: ['red', 'green'], // Color scale
    nodeRadius: 1, // Radius of the nodes
    strokeColor: '#ccc', // Color of the link lines
    strokeWidth: 1.5, // Width of the link lines
    childTextSize: 12, // Font size for child nodes
  },
  optionsDendrogram: {
    _selfKey: 'optionsDendrogram',
    margin: {
      top: 20, right: 120, bottom: 20, left: 120,
    },
    width: 960,
    height: 500,
    nodeRadius: 4.5,
    linkColor: '#ccc',
    nodeColor: 'steelblue',
    childTextSize: 10,
    fontColor: '#000',
  },
  optionsDonut: {
    _selfKey: 'optionsDonut',
    chartClass: 'donut',
    colorScheme: ['red', 'orange', 'yellow', 'green'],
    fontSize: 12,
    height: 800,
    hoverColor: 'blue',
    innerRadius: 180,
    margin: {
      bottom: 30,
      left: 100,
      right: 20,
      top: 20,
    },
    onHover: true,
    opacity: 0.05,
    outerRadius: 200,
    // stack: false,
    strokeColor: 'blue',
    strokeWidth: 10,
    textAnchor: 'middle',
    width: 900,
  },

  optionsFunnel: {
    _selfKey: 'optionsFunnel',
    colorScheme: ['blue', 'grey'],
    animate: true,
    // barWidth: 10,
    boxShadow: true,
    // gradient: true,
    // gradientAxis: 'y',
    // gradientColor: ['blue', 'red'],
    height: 500,
    hoverColor: 'blue',
    // isUpdating: false,
    margin: {
      top: 20,
      bottom: 30,
      left: 40,
      right: 20,
    },
    onHover: true,
    // opacity: 0.61,
    // sortBy: 'y asc',
    // stack: false,
    // textAnchor: 'middle',
    width: 960,
    xDomain: null,
    xLabel: 'xLabel',
    xLabelFontColor: 'black',
    xLabelFontFamily: 'Arial, sans-serif',
    xLabelFontSize: 12,
    xLabelFontOpacity: 1,
    xLabelFontWeight: 'bold',
    xLabelOffsetX: 0,
    xLabelOffsetY: 10,
    xLabelRotation: 90,
    xLine: false,
    xTickExtension: 0,
    xTickFontColor: '#333',
    xTickFontFamily: 'sans-serif',
    xTickFontOpacity: 1,
    xTickFontWeight: 'normal',
    xTickFontSize: 10,
    xTickFrequency: 10,
    xTickLength: 10,
    xTickOpacity: 1,
    xAxisColor: 'red',
    xAxisPosition: -1,
    yDomain: null,
    yLabel: 'yLabel',
    yLabelFontColor: 'black',
    yLabelFontFamily: 'Arial, sans-serif',
    yLabelFontSize: 12,
    yLabelFontOpacity: 1,
    yLabelFontWeight: 'bold',
    yLabelOffsetX: 0,
    yLabelOffsetY: 50,
    yLabelRotation: 0,
    yLine: false,
    yTickExtension: 100,
    yTickFontColor: '#333',
    yTickFontFamily: 'sans-serif',
    yTickFontOpacity: 0.55,
    yTickFontWeight: 'normal',
    yTickFontSize: 10,
    yTickFrequency: 10,
    yTickLength: 10,
    yAxisColor: 'blue',
    yAxisPosition: 880,
  },
  optionsIcicle: {
    _selfKey: 'optionsIcicle',
    margin: {
      top: 20, right: 120, bottom: 20, left: 120,
    },
    label: 'Root Category',
    width: 1200,
    height: 1000,
    colorScheme: ['red', 'pink', '#9ecae1', '#c6dbef', '#e6550d', '#fd8d3c', '#fdae6b', '#fdd0a2'],
    childTextSize: 12,
  },
  optionsHeat: {
    _selfKey: 'optionsHeat',
    // childTextSize: 10,
    colorScheme: ['red', 'blue'],
    // fontFamily: 'sans-seriff',
    // fontWeight: 'normal',
    height: 800,
    hoverColor: 'blue',
    margin: {
      bottom: 30, left: 40, right: 20, top: 20,
    },
    onHover: false,
    // padding: 0.1,
    // sortBy: 'value',
    // stack: false,
    // strokeColor: 'blue',
    textAnchor: 'middle',
    // textColor: 'white',
    width: 900,
    xLabel: 'xLabel',
    xTickExtension: 0,
    xTickFrequency: 10,
    xTickLength: 10,
    xTickOpacity: 1,
    xAxisColor: 'red',
    xAxisPosition: -1,
    xLabelOffsetX: 0,
    xLabelOffsetY: -50,
    xLabelRotation: 90,
    yLabel: 'yLabel',
    yTickExtension: 100,
    yTickFrequency: 10,
    yTickLength: 10,
    yTickOpacity: 0.55,
    yAxisColor: 'blue',
    yAxisPosition: 880,
    yLabelOffsetX: 0,
    yLabelOffsetY: 50,
    yLabelRotation: 0,
  },
  optionsLine: {
    _selfKey: 'optionsLine',
    animate: true,
    boxShadow: true,
    gradient: false,
    gradientAxis: 'y',
    gradientColor: ['red', 'yellow'],
    height: 500,
    hoverColor: 'blue',
    // isUpdating: false,
    margin: {
      top: 20,
      bottom: 30,
      left: 40,
      right: 20,
    },
    onHover: true,
    opacity: 0.61,
    sortBy: 'y asc',
    // stack: false,
    strokeColor: 'blue',
    strokeWidth: 8,
    width: 960,
    xDomain: null,
    xLabel: 'xLabel',
    xLabelFontColor: 'black',
    xLabelFontFamily: 'Arial, sans-serif',
    xLabelFontSize: 12,
    xLabelFontOpacity: 1,
    xLabelFontWeight: 'bold',
    xLabelOffsetX: 0,
    xLabelOffsetY: 10,
    xLabelRotation: 90,
    xLine: false,
    xTickExtension: 0,
    xTickFontColor: '#333',
    xTickFontFamily: 'sans-serif',
    xTickFontOpacity: 1,
    xTickFontWeight: 'normal',
    xTickFontSize: 10,
    xTickFrequency: 10,
    xTickLength: 10,
    xTickOpacity: 1,
    xAxisColor: 'red',
    xAxisPosition: -1,
    yDomain: null,
    yLabel: 'BOOOKS',
    yLabelFontColor: 'black',
    yLabelFontFamily: 'Arial, sans-serif',
    yLabelFontSize: 12,
    yLabelFontOpacity: 1,
    yLabelFontWeight: 'bold',
    yLabelOffsetX: 0,
    yLabelOffsetY: 50,
    yLabelRotation: 0,
    yLine: false,
    yTickExtension: 100,
    yTickFontColor: '#333',
    yTickFontFamily: 'sans-serif',
    yTickFontOpacity: 0.55,
    yTickFontWeight: 'normal',
    yTickFontSize: 10,
    yTickFrequency: 10,
    yTickLength: 10,
    yAxisColor: 'blue',
    yAxisPosition: 880,
  },

  optionsMarimekko: {
    _selfKey: 'optionsMarimekko',
    width: 1000, // The full width of the chart
    height: 600, // The full height of the chart
    margin: { // Margins for the chart
      top: 50,
      right: 50,
      bottom: 50,
      left: 50,
    },
    colorScheme: ['yellow', 'pink', '#9ecae1', '#c6dbef', '#e6550d', '#fd8d3c', '#fdae6b', '#fdd0a2'],
    xDomain: null,
    xLabel: 'X Axis',
    xLabelFontColor: 'green',
    xLabelFontFamily: 'Arial',
    xLabelFontSize: 14,
    xLabelFontOpacity: 1,
    xLabelFontWeight: 'normal',
    xLabelOffsetX: 10,
    xLabelOffsetY: -10,
    xLabelRotation: 0,
    xLine: true,
    xTickExtension: 5,
    xTickFontColor: '#000000',
    xTickFontFamily: 'Arial',
    xTickFontOpacity: 1,
    xTickFontWeight: 'normal',
    xTickFontSize: 12,
    xTickFrequency: 10,
    xTickLength: 5,
    xTickOpacity: 1,
    xAxisColor: '#000000',
    xAxisPosition: 490,
    yDomain: null,
    yLabel: 'Y Axis',
    yLabelFontColor: '#000000',
    yLabelFontFamily: 'Arial',
    yLabelFontSize: 14,
    yLabelFontOpacity: 1,
    yLabelFontWeight: 'normal',
    yLabelOffsetX: -10,
    yLabelOffsetY: 10,
    yLabelRotation: 0,
    yLine: true,
    yTickExtension: 5,
    yTickFontColor: '#000000',
    yTickFontFamily: 'Arial',
    yTickFontOpacity: 1,
    yTickFontWeight: 'normal',
    yTickFontSize: 12,
    yTickFrequency: 10,
    yTickLength: 5,
    yAxisColor: '#000000',
    yAxisPosition: 210,
  },
  optionsPie: {
    _selfKey: 'optionsPie',
    animate: true,
    chartClass: 'pie',
    colorScheme: ['red', 'orange', 'yellow', 'green'],
    fontColor: 'black',
    fontOpacity: 1,
    fontWeight: 'bold',
    fontSize: 12,
    height: 800,
    hoverColor: 'blue',
    innerRadius: 180,
    margin: {
      bottom: 30,
      left: 30,
      right: 20,
      top: 20,
    },
    onHover: true,
    opacity: 1,
    outerRadius: 200,
    radius: 100,
    // stack: false,
    showCategories: true,
    strokeColor: 'blue',
    strokeWidth: 10,
    textAnchor: 'middle',
    width: 900,
    xLabelFontSize: 12,
  },
  optionsPolar: {
    _selfKey: 'optionsPolar',
    colorScheme: ['#1f77b4', '#ff7f0e', '#2ca02c', '#d62728', '#9467bd'],
    fontSize: 12,
    fontColor: 'red',
    fontWeight: 'bold',
    fontOpacity: 1,
    height: 600,
    innerRadius: 50,
    opacity: 1,
    margin: {
      bottom: 20,
      left: 20,
      right: 20,
      top: 20,
    },
    outerRadius: 50,
    showCategories: true,
    textAnchor: 'middle',
    width: 600,
  },
  optionsScatter: {
    _selfKey: 'optionsScatter',
    animate: true,
    color: 'blue',
    boxShadow: true,
    gradient: false,
    gradientAxis: 'y',
    gradientColor: ['red', 'yellow'],
    height: 500,
    hoverColor: 'blue',
    isUpdating: false,
    margin: {
      top: 20,
      bottom: 30,
      left: 40,
      right: 20,
    },
    minNodeSize: 1,
    maxNodeSize: 100,
    nodeRadius: 10,
    onHover: true,
    opacity: 0.61,
    relativeNode: true,
    // sortBy: 'y asc',
    // stack: false,
    width: 960,
    xDomain: null,
    xLabel: 'xLabel',
    xLabelFontColor: 'black',
    xLabelFontFamily: 'Arial, sans-serif',
    xLabelFontSize: 12,
    xLabelFontOpacity: 1,
    xLabelFontWeight: 'bold',
    xLabelOffsetX: 0,
    xLabelOffsetY: 10,
    xLabelRotation: 90,
    xLine: false,
    xTickExtension: 0,
    xTickFontColor: '#333',
    xTickFontFamily: 'sans-serif',
    xTickFontOpacity: 1,
    xTickFontWeight: 'normal',
    xTickFontSize: 10,
    xTickFrequency: 10,
    xTickLength: 10,
    xTickOpacity: 1,
    xAxisColor: 'red',
    xAxisPosition: -1,
    yDomain: null,
    yLabel: 'yLabel',
    yLabelFontColor: 'black',
    yLabelFontFamily: 'Arial, sans-serif',
    yLabelFontSize: 12,
    yLabelFontOpacity: 1,
    yLabelFontWeight: 'bold',
    yLabelOffsetX: 0,
    yLabelOffsetY: 50,
    yLabelRotation: 0,
    yLine: false,
    yTickExtension: 100,
    yTickFontColor: '#333',
    yTickFontFamily: 'sans-serif',
    yTickFontOpacity: 0.55,
    yTickFontWeight: 'normal',
    yTickFontSize: 10,
    yTickFrequency: 10,
    yTickLength: 10,
    yAxisColor: 'blue',
    yAxisPosition: 880,
  },

  optionsStackedBar: {
    _selfKey: 'optionsStackedBar',
    width: 1000, // The full width of the chart
    height: 600, // The full height of the chart
    margin: { // Margins for the chart
      top: 50,
      right: 50,
      bottom: 50,
      left: 50,
    },
    colorScheme: ['red', 'pink', '#9ecae1', '#c6dbef', '#e6550d', '#fd8d3c', '#fdae6b', '#fdd0a2'],
    xDomain: null,
    xLabel: 'X Axis',
    xLabelFontColor: 'green',
    xLabelFontFamily: 'Arial',
    xLabelFontSize: 14,
    xLabelFontOpacity: 1,
    xLabelFontWeight: 'normal',
    xLabelOffsetX: 10,
    xLabelOffsetY: -10,
    xLabelRotation: 0,
    xLine: true,
    xTickExtension: 5,
    xTickFontColor: '#000000',
    xTickFontFamily: 'Arial',
    xTickFontOpacity: 1,
    xTickFontWeight: 'normal',
    xTickFontSize: 12,
    xTickFrequency: 10,
    xTickLength: 5,
    xTickOpacity: 1,
    xAxisColor: '#000000',
    xAxisPosition: 490,
    yDomain: null,
    yLabel: 'Y Axis',
    yLabelFontColor: '#000000',
    yLabelFontFamily: 'Arial',
    yLabelFontSize: 14,
    yLabelFontOpacity: 1,
    yLabelFontWeight: 'normal',
    yLabelOffsetX: -10,
    yLabelOffsetY: 10,
    yLabelRotation: 0,
    yLine: true,
    yTickExtension: 5,
    yTickFontColor: '#000000',
    yTickFontFamily: 'Arial',
    yTickFontOpacity: 1,
    yTickFontWeight: 'normal',
    yTickFontSize: 12,
    yTickFrequency: 10,
    yTickLength: 5,
    yAxisColor: '#000000',
    yAxisPosition: 210,
  },
  optionsRadar: {
    _selfKey: 'optionsRadar',
    colorScheme: ['#1f77b4', '#2ca02c'],
    fontColor: 'red',
    fontSize: 12,
    height: 500,
    levels: 50, // maybe should be calculated from data
    // margin: {
    //   bottom: 50,
    //   left: 50,
    //   right: 50,
    // top: 500,
    // },
    maxValue: 200, // maybe should be calculated from data
    width: 600,
    showCategories: true,
    strokeColor: 'red',
    strokeWidth: 1,
    xLabelFontSize: 23,
    textAnchor: 'middle',
  },
  optionsRadialTree: {
    _selfKey: 'optionsRadialTree',
    angle: 0,
    width: 1000,
    height: 1600,
    fillColor: 'blue',
    fontColor: 'red',
    fontFamily: 'papyrus',
    fontWeight: 'bold',
    radius: 400,
    nodeRadius: 8,
    nodeColor: 'red',
    linkColor: 'blue',
  },
  optionsSankey: {
    _selfKey: 'optionsSankey',
    colorScheme: ['red', 'blue', 'green', 'purple'],
    width: 800,
    height: 600,
    margin: {
      top: 20, right: 120, bottom: 20, left: 120,
    },
    nodeRadius: 15,
    nodePadding: 10,
    strokeColor: '#000',
    textAnchor: 'end',
  },
  optionsSun: {
    _selfKey: 'optionsSun',
    colorScheme: ['#FFB6C1', '#FFD700', '#ADFF2F', '#1E90FF', '#FF4500'],
    label: 'root category',
    width: 1160,
    height: 1700,
    radius: 200,
    childTextSize: 12,
  },
  optionsTreeDiagram: {
    _selfKey: 'optionsTreeDiagram',
    width: 1500, // The width of the entire tree diagram.
    height: 500, // The height of the entire tree diagram.
    margin: {
      top: 20, right: 20, bottom: 20, left: 20,
    },
    color: '#69b3a2', // The color of the nodes.
    fontColor: '#black', // The color of the nodes.
    radius: 10, // The radius of the nodes.
    strokeColor: '#555', // The color of the links between nodes.
    strokeWidth: 1.5, // The width of the links between nodes.
    opacity: 0.8, // The opacity of the links between nodes.
    childTextSize: 12, // The font size of the text labels.
  },
  optionsTreeMap: {
    _selfKey: 'optionsTreeMap',
    width: 1300,
    height: 1200,
    colorScheme: ['#ff7f0e', '#1f77b4', '#2ca02c', '#d62728', '#9467bd', '#8c564b', '#e377c2', '#7f7f7f', '#bcbd22', '#17becf'],
    childTextSize: 12,
  },
  optionsVoronoi: {
    _selfKey: 'optionsVoronoi',
    width: 800, // Width of the chart
    height: 600, // Height of the chart
    colorScheme: [ // Color scheme for the categories
      '#1f77b4', // blue
      '#ff7f0e', // orange
      '#2ca02c', // green
      '#d62728', // red
      '#9467bd', // purple
      '#8c564b', // brown
      '#e377c2', // pink
      '#7f7f7f', // gray
      '#bcbd22', // lime
      '#17becf', // teal
    ],
    strokeColor: '#000000', // Stroke color for the cells
    strokeWidth: 1, // Width of the stroke
    parentTextSize: 25, // Font size for parent category text
    childTextSize: 12, // Font size for child category text
    textAnchor: 'middle', // Alignment for the text within the cells
  },
  optionsWaterfall: {
    _selfKey: 'optionsWaterfall',
    barWidth: 10,
    color: 'steelblue',
    height: 400,
    margin: {
      bottom: 30,
      left: 50,
      right: 20,
      top: 20,
    },
    width: 600,
    xDomain: null,
    xLabel: 'X Axis',
    xLabelFontColor: 'green',
    xLabelFontFamily: 'Arial',
    xLabelFontSize: 14,
    xLabelFontOpacity: 1,
    xLabelFontWeight: 'normal',
    xLabelOffsetX: 10,
    xLabelOffsetY: -10,
    xLabelRotation: 0,
    xLine: true,
    xTickExtension: 5,
    xTickFontColor: '#000000',
    xTickFontFamily: 'Arial',
    xTickFontOpacity: 1,
    xTickFontWeight: 'normal',
    xTickFontSize: 12,
    xTickFrequency: 10,
    xTickLength: 5,
    xTickOpacity: 1,
    xAxisColor: '#000000',
    xAxisPosition: 490,
    yDomain: null,
    yLabel: 'Y Axis',
    yLabelFontColor: '#000000',
    yLabelFontFamily: 'Arial',
    yLabelFontSize: 14,
    yLabelFontOpacity: 1,
    yLabelFontWeight: 'normal',
    yLabelOffsetX: -10,
    yLabelOffsetY: 10,
    yLabelRotation: 0,
    yLine: true,
    yTickExtension: 5,
    yTickFontColor: '#000000',
    yTickFontFamily: 'Arial',
    yTickFontOpacity: 1,
    yTickFontWeight: 'normal',
    yTickFontSize: 12,
    yTickFrequency: 10,
    yTickLength: 5,
    yAxisColor: '#000000',
    yAxisPosition: 210,
  },
  //   optionsCluster: {
  //     width: 960,
  //     height: 800,
  //     nodeRadius: 10,
  //     strokeColor: '#ccc',
  //     strokeWidth: 2,
  //     childTextSize: '12px',
  //   },

};

// optionsBox: {
//   _selfKey: 'optionsBox',
//   animate: false,
//   boxShadow: true,
//   boxWidth: 10,
//   fillColor: 'blue',
//   gradient: false,
//   gradientAxis: 'y',
//   gradientColor: ['red', 'yellow'],
//   height: 500,
//   hoverColor: 'blue',
//   isUpdating: false,
//   margin: {
//     top: 20,
//     bottom: 30,
//     left: 40,
//     right: 20,
//   },
//   onHover: true,
//   opacity: 0.61,
//   sortBy: 'y asc',
//   stack: false,
//   textAnchor: 'middle',
//   width: 960,
//   xDomain: null,
//   xLabel: 'xLabel',
//   xLabelFontColor: 'black',
//   xLabelFontFamily: 'Arial, sans-serif',
//   xLabelFontSize: '12px',
//   xLabelFontOpacity: 1,
//   xLabelFontWeight: 'bold',
//   xLabelOffsetX: 0,
//   xLabelOffsetY: 10,
//   xLabelRotation: 90,
//   xLine: false,
//   xTickExtension: 0,
//   xTickFontColor: '#333',
//   xTickFontFamily: 'sans-serif',
//   xTickFontOpacity: 1,
//   xTickFontWeight: 'normal',
//   xTickFontSize: '10px',
//   xTickFrequency: 10,
//   xTickLength: 10,
//   xTickOpacity: 1,
//   xAxisColor: 'red',
//   xAxisPosition: -1,
//   yDomain: null,
//   yLabel: 'yLabel',
//   yLabelFontColor: 'black',
//   yLabelFontFamily: 'Arial, sans-serif',
//   yLabelFontSize: '12px',
//   yLabelFontOpacity: 1,
//   yLabelFontWeight: 'bold',
//   yLabelOffsetX: 0,
//   yLabelOffsetY: 50,
//   yLabelRotation: 0,
//   yLine: false,
//   yTickExtension: 100,
//   yTickFontColor: '#333',
//   yTickFontFamily: 'sans-serif',
//   yTickFontOpacity: 0.55,
//   yTickFontWeight: 'normal',
//   yTickFontSize: '10px',
//   yTickFrequency: 10,
//   yTickLength: 10,
//   yAxisColor: 'blue',
//   yAxisPosition: 880,
// },
// optionsDonut: {
//   _selfKey: 'optionsDonut',
//   colorScheme: ['red', 'orange', 'yellow', 'green'],
//   fontSize: 12,
//   height: 800,
//   hoverColor: 'blue',
//   innerRadius: 180,
//   margin: {
//     bottom: 30,
//     left: 100,
//     right: 20,
//     top: 20,
//   },
//   onHover: true,
//   opacity: 0.05,
//   outerRadius: 200,
//   stack: false,
//   strokeColor: 'blue',
//   strokeWidth: 10,
//   textAnchor: 'middle',
//   width: 900,
// },
// optionsBar: {
//   _selfKey: 'optionsBar',
//   animate: false,
//   barWidth: 0,
//   boxShadow: true,
//   fillColor: 'green',
//   gradient: false,
//   gradientAxis: 'y',
//   gradientColor: ['blue', 'red'],
//   height: 500,
//   hoverColor: 'blue',
//   isUpdating: false,
//   margin: {
//     top: 20,
//     bottom: 30,
//     left: 40,
//     right: 20,
//   },
//   onHover: true,
//   opacity: 0.61,
//   sortBy: 'y asc',
//   stack: false,
//   textAnchor: 'middle',
//   width: 960,
//   xDomain: null,
//   xLabel: 'xLabel',
//   xLabelFontColor: 'black',
//   xLabelFontFamily: 'Arial, sans-serif',
//   xLabelFontSize: '12px',
//   xLabelFontOpacity: 1,
//   xLabelFontWeight: 'bold',
//   xLabelOffsetX: 0,
//   xLabelOffsetY: 10,
//   xLabelRotation: 90,
//   xLine: false,
//   xTickExtension: 0,
//   xTickFontColor: '#333',
//   xTickFontFamily: 'sans-serif',
//   xTickFontOpacity: 1,
//   xTickFontWeight: 'normal',
//   xTickFontSize: '10px',
//   xTickFrequency: 10,
//   xTickLength: 10,
//   xTickOpacity: 1,
//   xAxisColor: 'red',
//   xAxisPosition: -1,
//   yDomain: [0, 100],
//   yLabel: 'yLabel',
//   yLabelFontColor: 'black',
//   yLabelFontFamily: 'Arial, sans-serif',
//   yLabelFontSize: '12px',
//   yLabelFontOpacity: 1,
//   yLabelFontWeight: 'bold',
//   yLabelOffsetX: 0,
//   yLabelOffsetY: 50,
//   yLabelRotation: 0,
//   yLine: false,
//   yTickExtension: 100,
//   yTickFontColor: '#333',
//   yTickFontFamily: 'sans-serif',
//   yTickFontOpacity: 0.55,
//   yTickFontWeight: 'normal',
//   yTickFontSize: '10px',
//   yTickFrequency: 10,
//   yTickLength: 10,
//   yAxisColor: 'blue',
//   yAxisPosition: 880,
// },
// optionsPie: {
//   _selfKey: 'optionsPie',
//   colorScale: null,
//   fontFamily: 'sans-seriff',
//   fontWeight: 'normal',
//   height: 600,
//   hoverColor: 'blue',
//   innerRadius: 180,
//   interval: 2000,
//   levels: 5, // maybe should be calculated from data
//   linkColor: 'black',
//   majorTickColor: 'black',
//   majorTicks: 5,
//   margin: {
//     bottom: 30, left: 40, right: 20, top: 20,
//   },
//   maxColor: 'red', // maybe should be d3 color scale
//   maxValue: 100, // maybe should be calculated from data
//   minColor: 'blue',
//   minorTickColor: 'black',
//   minorTicks: 4,
//   nodeRadius: 15,
//   onHover: true,
//   opacity: 0.75,
//   outerRadius: 200,
//   padding: 0.1,
//   parentTextSize: 12,
//   pointerColor: 'red',
//   pointerWidth: 10,
//   radius: 250,
//   showCategories: true,
//   sortBy: 'value',
//   stack: false,
//   strokeColor: 'blue',
//   textAnchor: 'middle',
//   textColor: 'white',
//   width: 900,
// },
// options8: {
//   _selfKey: 'options8',
//   // animate: true,
//   barWidth: 10,
//   boxShadow: true,
//   color: 'green',
//   diameter: 100,
//   fillColor: ['red', 'blue', 'green', 'yellow', 'orange', 'purple'],
//   height: 900,
//   hoverColor: 'red',
//   margin: {
//     bottom: 30,
//     left: 40,
//     right: 20,
//     top: 20,
//   },
//   onHover: false,
//   opacity: 1,
//   radius: 50.5,
//   stack: false,
//   textAnchor: 'middle',
//   textColor: 'white',
//   width: 1600,
//   xLabel: 'xLabel',
//   xFontColor: 'red',
//   xFontFamily: 'gothic',
//   xFontOpacity: 1,
//   // xFontSize: 10,
//   // xFontStyle: 'italic',
//   xFontWeight: 'bold',
//   xLabelFontColor: 'blue',
//   xLabelFontFamily: 'sans-serif',
//   xLabelFontWeight: 'bold',
//   xLabelOffsetX: 0,
//   xLabelOffsetY: -50,
//   xLabelRotation: 90,
//   xLine: true,
//   xAxisColor: 'red',
//   xAxisOpacity: 1,
//   xAxisPosition: -1,
//   xTextAnchor: 'start',
//   xTickExtension: 1,
//   xTickFrequency: 10,
//   xTickLength: 10,
//   yFontColor: 'blue',
//   yFontFamily: 'sans-serif',
//   yFontOpacity: 1,
//   // yFontSize: 10,
//   // yFontStyle: 'italic',
//   yFontWeight: 'bold',
//   yLabel: 'yLabel',
//   yLabelFontColor: 'red',
//   yLabelFontFamily: 'gothic',
//   yLabelFontWeight: 'bold',
//   yLabelOffsetX: 0,
//   yLabelOffsetY: 50,
//   yLabelRotation: 0,
//   yLine: true,
//   yAxisColor: 'purple',
//   yAxisOpacity: 1,
//   yAxisPosition: 420,
//   yTickExtension: 1,
//   yTickFrequency: 10,
//   yTickLength: 10,
//   yTickOpacity: 1,
// },
// optionsLine: {
//   _selfKey: 'optionsLine',
//   // animate: false,
//   boxShadow: true,
//   gradient: false,
//   gradientAxis: 'y',
//   gradientColor: ['red', 'yellow'],
//   height: 500,
//   hoverColor: 'blue',
//   // isUpdating: false,
//   margin: {
//     top: 20,
//     bottom: 30,
//     left: 40,
//     right: 20,
//   },
//   onHover: true,
//   opacity: 0.61,
//   sortBy: 'y asc',
//   // stack: false,
//   strokeColor: 'blue',
//   strokeWidth: 8,
//   width: 960,
//   xDomain: ['number'],
//   xLabel: 'xLabel',
//   xLabelFontColor: 'black',
//   xLabelFontFamily: 'Arial, sans-serif',
//   xLabelFontSize: '12px',
//   xLabelFontOpacity: 1,
//   xLabelFontWeight: 'bold',
//   xLabelOffsetX: 0,
//   xLabelOffsetY: 10,
//   xLabelRotation: 90,
//   xLine: false,
//   xTickExtension: 0,
//   xTickFontColor: '#333',
//   xTickFontFamily: 'sans-serif',
//   xTickFontOpacity: 1,
//   xTickFontWeight: 'normal',
//   xTickFontSize: '10px',
//   xTickFrequency: 10,
//   xTickLength: 10,
//   xTickOpacity: 1,
//   xAxisColor: 'red',
//   xAxisPosition: -1,
//   yDomain: ['number'],
//   yLabel: 'yLabel',
//   yLabelFontColor: 'black',
//   yLabelFontFamily: 'Arial, sans-serif',
//   yLabelFontSize: '12px',
//   yLabelFontOpacity: 1,
//   yLabelFontWeight: 'bold',
//   yLabelOffsetX: 0,
//   yLabelOffsetY: 50,
//   yLabelRotation: 0,
//   yLine: false,
//   yTickExtension: 100,
//   yTickFontColor: '#333',
//   yTickFontFamily: 'sans-serif',
//   yTickFontOpacity: 0.55,
//   yTickFontWeight: 'normal',
//   yTickFontSize: '10px',
//   yTickFrequency: 10,
//   yTickLength: 10,
//   yAxisColor: 'blue',
//   yAxisPosition: 880,
// },
// optionsBubble: {
//   _selfKey: 'optionsBubble',
//   barWidth: 10,
//   bubble: true,
//   bubbleOpacity: 0.7,
//   chargeStrength: 0.01,
//   childTextSize: 9,
//   colorScheme: ['red', 'blue'],
//   diameter: 50,
//   fontColor: 'black',
//   height: 2600,
//   maxRadius: 100,
//   menu: 'dropdown',
//   padding: 5,
//   parentTextSize: 12,
//   textAnchor: 'middle',
//   width: 2800,
// },
// optionsForceDirected: {
//   _selfKey: 'optionsForceDirected',
//   chargeStrength: -200,
//   height: 600,
//   linkDistance: 50,
//   width: 600,
//   xTickExtension: 0,
//   xTickFrequency: 10,
//   xTickLength: 10,
//   xTickOpacity: 1,
//   xAxisColor: 'red',
//   xAxisPosition: -1,
//   xLabelOffsetX: 0,
//   xLabelOffsetY: -50,
//   xLabelRotation: 90,
//   yTickExtension: 100,
//   yTickFrequency: 10,
//   yTickLength: 10,
//   yTickOpacity: 0.55,
//   yAxisColor: 'blue',
//   yAxisPosition: 880,
//   yLabelOffsetX: 0,
//   yLabelOffsetY: 50,
//   yLabelRotation: 0,
//   barWidth: 10,
// },
// optionsPolar: {
//   _selfKey: 'optionsPolar',
//   barWidth: 10,
//   colorScheme: ['#1f77b4', '#ff7f0e', '#2ca02c', '#d62728', '#9467bd'],
//   fontSize: 12,
//   height: 600,
//   innerRadius: 50,
//   margin: {
//     bottom: 20,
//     left: 20,
//     right: 20,
//     top: 20,
//   },
//   outerRadius: 250,
//   textAnchor: 'middle',
//   width: 600,
// },
// optionsRadar: {
//   _selfKey: 'optionsRadar',
//   barWidth: 10,
//   colors: ['#1f77b4', '#2ca02c'],
//   height: 500,
//   levels: 5, // maybe should be calculated from data
//   margin: {
//     bottom: 50,
//     left: 50,
//     right: 50,
//     top: 50,
//   },
//   maxValue: 100, // maybe should be calculated from data
//   width: 600,
// },
// optionsScatter: {
//   _selfKey: 'optionsScatter',
//   // animate: false,
//   boxShadow: true,
//   gradient: false,
//   gradientAxis: 'y',
//   gradientColor: ['red', 'yellow'],
//   height: 500,
//   hoverColor: 'blue',
//   isUpdating: false,
//   margin: {
//     top: 20,
//     bottom: 30,
//     left: 40,
//     right: 20,
//   },
//   onHover: true,
//   opacity: 0.61,
//   relativeNode: true,
//   sortBy: 'y asc',
//   // stack: false,
//   width: 960,
//   xDomain: ['number'],
//   xLabel: 'xLabel',
//   xLabelFontColor: 'black',
//   xLabelFontFamily: 'Arial, sans-serif',
//   xLabelFontSize: '12px',
//   xLabelFontOpacity: 1,
//   xLabelFontWeight: 'bold',
//   xLabelOffsetX: 0,
//   xLabelOffsetY: 10,
//   xLabelRotation: 90,
//   xLine: false,
//   xTickExtension: 0,
//   xTickFontColor: '#333',
//   xTickFontFamily: 'sans-serif',
//   xTickFontOpacity: 1,
//   xTickFontWeight: 'normal',
//   xTickFontSize: '10px',
//   xTickFrequency: 10,
//   xTickLength: 10,
//   xTickOpacity: 1,
//   xAxisColor: 'red',
//   xAxisPosition: -1,
//   yDomain: ['number'],
//   yLabel: 'yLabel',
//   yLabelFontColor: 'black',
//   yLabelFontFamily: 'Arial, sans-serif',
//   yLabelFontSize: '12px',
//   yLabelFontOpacity: 1,
//   yLabelFontWeight: 'bold',
//   yLabelOffsetX: 0,
//   yLabelOffsetY: 50,
//   yLabelRotation: 0,
//   yLine: false,
//   yTickExtension: 100,
//   yTickFontColor: '#333',
//   yTickFontFamily: 'sans-serif',
//   yTickFontOpacity: 0.55,
//   yTickFontWeight: 'normal',
//   yTickFontSize: '10px',
//   yTickFrequency: 10,
//   yTickLength: 10,
//   yAxisColor: 'blue',
//   yAxisPosition: 880,
// },
// optionsWaterfall: {
//   _selfKey: 'optionsWaterfall',
//   barWidth: 10,
//   color: 'steelblue',
//   height: 400,
//   margin: {
//     bottom: 30,
//     left: 50,
//     right: 20,
//     top: 20,
//   },
//   width: 600,
//   xAxisColor: 'red',
//   xAxisPosition: -1,
//   xDomain: ['number'],
//   xLabelOffsetX: 0,
//   xLabelOffsetY: -50,
//   xLabelRotation: 90,
//   xLine: true,
//   xTickExtension: 0,
//   xTickFontColor: '#333',
//   xTickFontFamily: 'sans-serif',
//   xTickFontOpacity: 1,
//   xTickFontWeight: 'normal',
//   xTickFontSize: '10px',
//   xTickFrequency: 10,
//   xTickLength: 10,
//   xTickOpacity: 1,
//   yAxisColor: 'purple',
//   yAxisPosition: 0,
//   yDomain: [0, 100],
//   yLabelOffsetX: 0,
//   yLabelOffsetY: 50,
//   yLabelRotation: 0,
//   yLine: true,
//   yTickExtension: 100,
//   yTickFontColor: '#333',
//   yTickFontFamily: 'sans-serif',
//   yTickFontOpacity: 0.55,
//   yTickFontWeight: 'normal',
//   yTickFontSize: '10px',
//   yTickFrequency: 10,
//   yTickLength: 10,
//   yTickOpacity: 0.55,
// },
// optionsGauge: {
//   _selfKey: 'gauge',
//   height: 300,
//   interval: 2000,
//   majorTickColor: 'black',
//   majorTicks: 5,
//   margin: {
//     bottom: 30,
//     left: 40,
//     right: 20,
//     top: 20,
//   },
//   minorTickColor: 'black',
//   minorTicks: 4,
//   pointerColor: 'red',
//   pointerWidth: 10,
//   startAngle: -Math.PI / 1.25,
//   endAngle: Math.PI / 1.25,
//   width: 300,

// },
// optionsHeat: {
//   _selfKey: 'optionsHeat',
//   childTextSize: 10,
//   color: 'red',
//   fillColor: 'blue',
//   fontFamily: 'sans-seriff',
//   fontWeight: 'normal',
//   height: 800,
//   hoverColor: 'blue',
//   margin: {
//     bottom: 30, left: 40, right: 20, top: 20,
//   },
//   onHover: false,
//   opacity: 0.75,
//   padding: 0.1,
//   sortBy: 'value',
//   stack: false,
//   strokeColor: 'blue',
//   // textAnchor: 'middle',
//   // textColor: 'white',
//   width: 900,
//   xLabel: 'xLabel',
//   xTickExtension: 0,
//   xTickFrequency: 10,
//   xTickLength: 10,
//   xTickOpacity: 1,
//   xAxisColor: 'red',
//   xAxisPosition: -1,
//   xLabelOffsetX: 0,
//   xLabelOffsetY: -50,
//   xLabelRotation: 90,
//   yLabel: 'yLabel',
//   yTickExtension: 100,
//   yTickFrequency: 10,
//   yTickLength: 10,
//   yTickOpacity: 0.55,
//   yAxisColor: 'blue',
//   yAxisPosition: 880,
//   yLabelOffsetX: 0,
//   yLabelOffsetY: 50,
//   yLabelRotation: 0,
// },
