export const optionData = {};

optionData.options0 = {
  childTextSize: 10,
  color: d3.scaleOrdinal(d3.schemeCategory10),
  diameter: 600,
  endAngle: Math.PI / 1.25,
  fillColor: 'blue',
  fontFamily: 'sans-seriff',
  fontWeight: 'normal',
  height: 800,
  hoverColor: 'blue',
  innerRadius: 180,
  interval: 2000,
  levels: 5, // maybe should be calculated from data
  linkColor: 'black',
  majorTickColor: 'black',
  majorTicks: 5,
  margin: {
    bottom: 30, left: 40, right: 20, top: 20,
  },
  maxColor: 'red', // maybe should be d3 color scale
  maxValue: 100, // maybe should be calculated from data
  minColor: 'blue',
  minorTickColor: 'black',
  minorTicks: 4,
  nodeRadius: 15,
  onHover: false,
  opacity: 0.75,
  outerRadius: 200,
  overlay: true,
  padding: 0.1,
  parentTextSize: 12,
  pointerColor: 'red',
  pointerWidth: 10,
  radius: 10,
  showCategories: true,
  showLabels: true,
  sortBy: 'value',
  stack: false,
  startAngle: -Math.PI / 1.25,
  strokeColor: 'blue',
  textAnchor: 'middle',
  textColor: 'white',
  width: 900,
  xLabel: 'xLabel',
  yLabel: 'yLabel',
  xTickFrequency: 10,
  yTickFrequency: 10,
  xTickLength: 10,
  yTickLength: 10,
  xTickExtension: 0,
  yTickExtension: 100,
  xTickOpacity: 1,
  yTickOpacity: 0.55,
  xAxisColor: 'red',
  yAxisColor: 'blue',
  xAxisPosition: -1,
  yAxisPosition: 880,
  yLabelOffsetX: 0,
  yLabelOffsetY: 50,
  yLabelRotation: 0,
  xLabelOffsetX: 0,
  xLabelOffsetY: -50,
  xLabelRotation: 90,
  barWidth: 10,
};

optionData.options2 = {
  margin: {
    top: 20, right: 20, bottom: 30, left: 40,
  },
  width: 800,
  height: 600,
  radius: 10.5,
  color: 'red',
  fontColor: 'blue',
  showCategories: true,
  diameter: 400,
  fillColor: ['red', 'blue', 'green', 'yellow', 'orange', 'purple'],
  // onHover: true,
  overlay: true,
  opacity: 0.61,
  stack: false,
  sortBy: 'y asc',
  xLine: false,
  yLine: false,
  textAnchor: 'middle',
  childTextSize: 5,
  parentTextSize: 10,
  xTickFrequency: 10,
  yTickFrequency: 10,
  xTickLength: 10,
  yTickLength: 10,
  xTickExtension: 0,
  yTickExtension: 100,
  xTickOpacity: 1,
  yTickOpacity: 0.55,
  xAxisColor: 'red',
  yAxisColor: 'blue',
  xAxisPosition: -1,
  yAxisPosition: 880,
  yLabelOffsetX: 0,
  yLabelOffsetY: 50,
  yLabelRotation: 0,
  xLabelOffsetX: 0,
  xLabelOffsetY: -50,
  xLabelRotation: 90,
  barWidth: 10,
};

optionData.options3 = {
  childTextSize: 10,
  strokeColor: 'blue',
  diameter: 600,
  duration: 1000,
  radius: 200,
  barWidth: -50,
  parentTextSize: 12,
  textAnchor: 'middle',
  margin: {
    top: 20, right: 20, bottom: 30, left: 40,
  },
  width: 800,
  height: 600,
  colorScale: d3.interpolateRdYlBu, // use a diverging color scale
  fillColor: '#1f77b4', // color used to fill the area chart
  xLabel: 'X Axis Label',
  yLabel: 'Y Axis Label',
  outerRadius: 500,
  innerRadius: 150,
  colorScheme: d3.schemeCategory10,
  overlay: false,
  onHover: false,
  opacity: 1,
  color: d3.scaleOrdinal(d3.schemeCategory10),
  // color: 'red',
  nodeWidth: 10,
  nodePadding: 1,
  yLine: true,
  xLine: true,
  xTickFrequency: 10,
  yTickFrequency: 10,
  xTickLength: 10,
  yTickLength: 10,
  xTickExtension: 1,
  yTickExtension: 1,
  xTickOpacity: 1,
  yTickOpacity: 1,
  xAxisColor: 'red',
  yAxisColor: 'purple',
  xAxisOpacity: 1,
  yAxisOpacity: 1,
  xTickFontSize: 10,
  yTickFontSize: 10,
  xFontColor: 'red',
  yFontColor: 'blue',
  xFontWeight: 'bold',
  yFontWeight: 'bold',
  xFontFamily: 'gothic',
  yFontFamily: 'sans-serif',
  yLabelFontColor: 'red',
  xLabelFontColor: 'blue',
  xFontOpacity: 1,
  yFontOpacity: 1,
  xFontStyle: 'italic',
  yFontStyle: 'italic',
  xTextAnchor: 'start',
  xLabelOffsetX: 10,
  xLabelOffsetY: 10,
  xLabelRotation: 90,
  yLabelOffsetX: 300,
  yLabelOffsetY: 100,
  yLabelRotation: 0,
  yLabelFontSize: 60,
  xLabelFontSize: 60,
};

optionData.options4 = {
  margin: {
    top: 20, right: 20, bottom: 30, left: 40,
  },
  width: 900,
  height: 800,
  opacity: 0.75,
  onHover: false,
  radius: 200,
  color: 'blue',
  colorScheme: d3.schemeCategory10,
  showLabels: true,
  diameter: 6,
  stack: false,
  // fillColor: ['red', 'blue', 'green', 'yellow', 'orange', 'purple'],
  fillColor: 'red',
  strokeColor: 'blue',
  xLabel: 'xLabel',
  yLabel: 'yLabel',
  xLine: true,
  yLine: true,
  colorScale: 'red',
  overlay: false,
  // colorScheme: d3.schemeCategory10,
  xTickFrequency: 10,
  yTickFrequency: 10,
  xTickLength: 10,
  yTickLength: 10,
  xTickExtension: 0,
  yTickExtension: 100,
  xTickOpacity: 1,
  yTickOpacity: 0.55,
  xAxisColor: 'red',
  yAxisColor: 'blue',
  xAxisPosition: -1,
  yAxisPosition: 880,
  yLabelOffsetX: 0,
  yLabelOffsetY: 50,
  yLabelRotation: 0,
  xLabelOffsetX: 0,
  xLabelOffsetY: -50,
  xLabelRotation: 90,
  barWidth: 10,
};

optionData.options5 = {
  width: 900,
  height: 600,
  margin: {
    bottom: 30, left: 40, right: 20, top: 20,
  },
  color: 'steelblue',
  fillColor: 'steelblue',
  // onHover: true,
  overlay: false,
  diameter: 600,
  opacity: 0.5,
  stack: true,
  xTickFrequency: 10,
  yTickFrequency: 10,
  xTickLength: 10,
  yTickLength: 10,
  xTickExtension: 0,
  yTickExtension: 100,
  xTickOpacity: 1,
  yTickOpacity: 0.55,
  xAxisColor: 'red',
  yAxisColor: 'blue',
  xAxisPosition: -1,
  yAxisPosition: 880,
  yLabelOffsetX: 0,
  yLabelOffsetY: 50,
  yLabelRotation: 0,
  xLabelOffsetX: 0,
  xLabelOffsetY: -50,
  xLabelRotation: 90,
  barWidth: 10,
};

optionData.waterfall = {
  width: 600,
  height: 400,
  margin: {
    top: 20,
    right: 20,
    bottom: 30,
    left: 50,
  },
  color: 'steelblue',
  positiveColor: 'green',
  negativeColor: 'red',
  overlay: false,
  xTickFrequency: 10,
  yTickFrequency: 10,
  xTickLength: 10,
  yTickLength: 10,
  xTickExtension: 0,
  yTickExtension: 100,
  xTickOpacity: 1,
  yTickOpacity: 0.55,
  xAxisColor: 'red',
  yAxisColor: 'blue',
  xAxisPosition: -1,
  yAxisPosition: 880,
  yLabelOffsetX: 0,
  yLabelOffsetY: 50,
  yLabelRotation: 0,
  xLabelOffsetX: 0,
  xLabelOffsetY: -50,
  xLabelRotation: 90,
  barWidth: 10,
};

optionData.funnelChart = {
  width: 800,
  height: 400,
  margin: {
    top: 20, right: 20, bottom: 30, left: 100,
  },
  colors: ['steelblue', 'grey'],
  overlay: false,
  onHover: false,
  nodeWidth: 10,
  nodePadding: 1,
  padding: 2,
  strokeColor: '#000000',
  radius: 10,
  yLine: true,
  xLine: true,
  xTickFrequency: 10,
  yTickFrequency: 10,
  xTickLength: 10,
  yTickLength: 10,
  xTickExtension: 0,
  yTickExtension: 100,
  xTickOpacity: 1,
  yTickOpacity: 0.55,
  xAxisColor: 'red',
  yAxisColor: 'blue',
  xAxisPosition: -1,
  yAxisPosition: 880,
  yLabelOffsetX: 0,
  yLabelOffsetY: 50,
  yLabelRotation: 0,
  xLabelOffsetX: 0,
  xLabelOffsetY: -50,
  xLabelRotation: 90,
  barWidth: 10,
};

optionData.polarChart = {
  width: 600,
  height: 600,
  margin: {
    top: 20, right: 20, bottom: 20, left: 20,
  },
  colors: ['#1f77b4', '#ff7f0e', '#2ca02c', '#d62728', '#9467bd'],
  innerRadius: 50,
  outerRadius: 250,
  overlay: false,
  xTickFrequency: 10,
  yTickFrequency: 10,
  xTickLength: 10,
  yTickLength: 10,
  xTickExtension: 0,
  yTickExtension: 100,
  xTickOpacity: 1,
  yTickOpacity: 0.55,
  xAxisColor: 'red',
  yAxisColor: 'blue',
  xAxisPosition: -1,
  yAxisPosition: 880,
  yLabelOffsetX: 0,
  yLabelOffsetY: 50,
  yLabelRotation: 0,
  xLabelOffsetX: 0,
  xLabelOffsetY: -50,
  xLabelRotation: 90,
  barWidth: 10,
};

optionData.radarChart = {
  width: 500,
  height: 500,
  margin: {
    top: 50, right: 50, bottom: 50, left: 50,
  },
  colors: ['#1f77b4', '#2ca02c'],
  maxValue: 100, // maybe should be calculated from data
  levels: 5, // maybe should be calculated from data
  overlay: false,
  xTickFrequency: 10,
  yTickFrequency: 10,
  xTickLength: 10,
  yTickLength: 10,
  xTickExtension: 0,
  yTickExtension: 100,
  xTickOpacity: 1,
  yTickOpacity: 0.55,
  xAxisColor: 'red',
  yAxisColor: 'blue',
  xAxisPosition: -1,
  yAxisPosition: 880,
  yLabelOffsetX: 0,
  yLabelOffsetY: 50,
  yLabelRotation: 0,
  xLabelOffsetX: 0,
  xLabelOffsetY: -50,
  xLabelRotation: 90,
  barWidth: 10,
};

optionData.gauge = {
  margin: {
    top: 20, right: 20, bottom: 30, left: 40,
  },
  width: 300,
  height: 300,
  majorTicks: 5,
  minorTicks: 4,
  startAngle: -Math.PI / 1.25,
  endAngle: Math.PI / 1.25,
  pointerColor: 'red',
  majorTickColor: 'black',
  minorTickColor: 'black',
  interval: 2000,
  pointerWidth: 10,
  overlay: false,
  xTickFrequency: 10,
  yTickFrequency: 10,
  xTickLength: 10,
  yTickLength: 10,
  xTickExtension: 0,
  yTickExtension: 100,
  xTickOpacity: 1,
  yTickOpacity: 0.55,
  xAxisColor: 'red',
  yAxisColor: 'blue',
  xAxisPosition: -1,
  yAxisPosition: 880,
  yLabelOffsetX: 0,
  yLabelOffsetY: 50,
  yLabelRotation: 0,
  xLabelOffsetX: 0,
  xLabelOffsetY: -50,
  xLabelRotation: 90,
  barWidth: 10,
};

optionData.optionsForceDirected = {
  width: 600,
  height: 600,
  //   color: d3.scaleOrdinal(d3.schemeCategory10),
  linkDistance: 50, // TODO look into linkdistance
  chargeStrength: -200, // TODO look into chargeStrength
  xTickFrequency: 10,
  yTickFrequency: 10,
  xTickLength: 10,
  yTickLength: 10,
  xTickExtension: 0,
  yTickExtension: 100,
  xTickOpacity: 1,
  yTickOpacity: 0.55,
  xAxisColor: 'red',
  yAxisColor: 'blue',
  xAxisPosition: -1,
  yAxisPosition: 880,
  yLabelOffsetX: 0,
  yLabelOffsetY: 50,
  yLabelRotation: 0,
  xLabelOffsetX: 0,
  xLabelOffsetY: -50,
  xLabelRotation: 90,
  barWidth: 10,
};

optionData.options1 = {
  childTextSize: 10,
  color: 'red',
  colorScale: 'red',
  diameter: 600,
  endAngle: Math.PI / 1.25,
  fillColor: 'blue',
  fontFamily: 'sans-seriff',
  fontWeight: 'normal',
  gradient: true,
  gradientAxis: 'x',
  gradientColor: ['red', 'yellow'],
  height: 600,
  hoverColor: 'blue',
  innerRadius: 180,
  interval: 2000,
  levels: 5, // maybe should be calculated from data
  linkColor: 'black',
  majorTickColor: 'black',
  majorTicks: 5,
  margin: {
    bottom: 30, left: 40, right: 20, top: 20,
  },
  maxColor: 'red', // maybe should be d3 color scale
  maxValue: 100, // maybe should be calculated from data
  minColor: 'blue',
  minorTickColor: 'black',
  minorTicks: 4,
  nodeRadius: 15,
  onHover: false,
  opacity: 1,
  outerRadius: 200,
  overlay: true,
  padding: 0.1,
  parentTextSize: 12,
  pointerColor: 'red',
  pointerWidth: 10,
  radius: 10,
  showCategories: true,
  showLabels: true,
  sortBy: 'value',
  stack: true,
  startAngle: -Math.PI / 1.25,
  strokeColor: 'blue',
  textAnchor: 'middle',
  textColor: 'white',
  width: 900,
  xLabel: 'xLabel',
  yLabel: 'yLabel',
  xTickFrequency: 10,
  yTickFrequency: 10,
  xTickLength: 10,
  yTickLength: 10,
  xTickExtension: 1,
  yTickExtension: 1,
  xTickOpacity: 0.21,
  yTickOpacity: 0.1,
  xAxisColor: 'red',
  yAxisColor: 'blue',
  xLabelOffsetY: 10,
  xLabelOffsetX: 10,
  yLabelOffsetY: 10,
  yLabelOffsetX: 10,
  xLabelRotation: 0,
  yLabelRotation: 0,
};

optionData.options13 = {
  childTextSize: 10,
  color: 'red',
  colorScale: 'red',
  diameter: 600,
  duration: 500,
  endAngle: Math.PI / 1.25,
  fillColor: 'red',
  fontFamily: 'sans-seriff',
  fontWeight: 'normal',
  gradient: false,
  gradientAxis: 'x',
  gradientColor: ['red', 'yellow'],
  height: 600,
  hoverColor: 'blue',
  innerRadius: 180,
  interval: 2000,
  levels: 5, // maybe should be calculated from data
  linkColor: 'black',
  majorTickColor: 'black',
  majorTicks: 5,
  margin: {
    bottom: 30, left: 40, right: 20, top: 20,
  },
  maxColor: 'red', // maybe should be d3 color scale
  maxValue: 100, // maybe should be calculated from data
  minColor: 'blue',
  minorTickColor: 'black',
  minorTicks: 4,
  nodeRadius: 15,
  onHover: true,
  opacity: 0.75,
  outerRadius: 200,
  overlay: true,
  padding: 0.1,
  parentTextSize: 12,
  pointerColor: 'red',
  pointerWidth: 10,
  radius: 10,
  relativeNode: true,
  showCategories: true,
  showLabels: true,
  sortBy: 'value',
  stack: false,
  startAngle: -Math.PI / 1.25,
  strokeColor: 'blue',
  textAnchor: 'middle',
  textColor: 'white',
  width: 900,
  xAxisPosition: -1,
  xLabel: 'xLabel',
  xLine: true,
  yAxisPosition: 880,
  barWidth: -30,
  yLabel: 'yLabel',
  yLine: false,
  xTickFrequency: 30,
  yTickFrequency: 30,
  xTickLength: 600,
  yTickLength: 900,
  xTickExtension: -580,
  yTickExtension: 880,
  xTickOpacity: 1,
  yTickOpacity: 1,
  xAxisColor: 'red',
  yAxisColor: 'blue',
  yLabelOffsetX: 0,
  yLabelOffsetY: 0,
  xLabelOffsetX: 0,
  xLabelOffsetY: 0,
  xLabelColor: 'red',
  yLabelColor: 'blue',
  xLabelFontSize: 10,
  yLabelFontSize: 10,
  xLabelFontWeight: 'normal',
  yLabelFontWeight: 'normal',
  xLabelFontFamily: 'sans-serif',
  yLabelFontFamily: 'sans-serif',
  xLabelRotation: 0,
  yLabelRotation: 0,
};

optionData.options14 = {
  childTextSize: 10,
  color: 'green',
  colorScale: 'red',
  diameter: 600,
  endAngle: Math.PI / 1.25,
  fillColor: 'blue',
  fontFamily: 'sans-seriff',
  fontWeight: 'normal',
  height: 800,
  hoverColor: 'blue',
  innerRadius: 180,
  interval: 2000,
  levels: 5, // maybe should be calculated from data
  linkColor: 'black',
  majorTickColor: 'black',
  majorTicks: 5,
  margin: {
    bottom: 30, left: 40, right: 20, top: 20,
  },
  maxColor: 'red', // maybe should be d3 color scale
  maxValue: 100, // maybe should be calculated from data
  minColor: 'blue',
  minorTickColor: 'black',
  minorTicks: 4,
  nodeRadius: 15,
  onHover: false,
  opacity: 0.75,
  outerRadius: 200,
  overlay: true,
  padding: 0.1,
  parentTextSize: 12,
  pointerColor: 'red',
  pointerWidth: 10,
  radius: 10,
  showCategories: true,
  showLabels: true,
  sortBy: 'value',
  stack: false,
  startAngle: -Math.PI / 1.25,
  strokeColor: 'blue',
  textAnchor: 'middle',
  textColor: 'white',
  width: 900,
  xLabel: 'xLabel',
  yLabel: 'yLabel',
  xTickFrequency: 10,
  yTickFrequency: 10,
  xTickLength: 10,
  yTickLength: 10,
  xTickExtension: 0,
  yTickExtension: 100,
  xTickOpacity: 1,
  yTickOpacity: 0.55,
  xAxisColor: 'red',
  yAxisColor: 'blue',
  xAxisPosition: -1,
  yAxisPosition: 880,
  yLabelOffsetX: 0,
  yLabelOffsetY: 50,
  yLabelRotation: 0,
  xLabelOffsetX: 0,
  xLabelOffsetY: -50,
  xLabelRotation: 90,
  barWidth: 10,
};

optionData.options15 = {
  childTextSize: 10,
  color: 'green',
  colorScale: 'red',
  diameter: 400,
  endAngle: Math.PI / 1.25,
  fillColor: 'blue',
  fontFamily: 'sans-seriff',
  fontWeight: 'normal',
  height: 600,
  hoverColor: 'blue',
  innerRadius: 180,
  interval: 2000,
  levels: 5, // maybe should be calculated from data
  linkColor: 'black',
  majorTickColor: 'black',
  majorTicks: 5,
  margin: {
    bottom: 30, left: 40, right: 20, top: 20,
  },
  maxColor: 'red', // maybe should be d3 color scale
  maxValue: 100, // maybe should be calculated from data
  minColor: 'blue',
  minorTickColor: 'black',
  minorTicks: 4,
  nodeRadius: 15,
  onHover: false,
  opacity: 1,
  outerRadius: 200,
  overlay: true,
  padding: 0.1,
  parentTextSize: 12,
  pointerColor: 'red',
  pointerWidth: 10,
  radius: 10,
  // relativeNodeSize: true,
  showCategories: true,
  showLabels: true,
  sortBy: 'value',
  stack: false,
  startAngle: -Math.PI / 1.25,
  strokeColor: 'blue',
  textAnchor: 'middle',
  textColor: 'white',
  width: 900,
  xLabel: 'xLabel',
  xLine: false,
  yLine: false,
  yLabel: 'yLabel',
  xTickFrequency: 10,
  yTickFrequency: 10,
  xTickLength: 10,
  yTickLength: 10,
  xTickExtension: 0,
  yTickExtension: 100,
  xTickOpacity: 1,
  yTickOpacity: 0.55,
  xAxisColor: 'red',
  yAxisColor: 'blue',
  xAxisPosition: -1,
  yAxisPosition: 880,
  yLabelOffsetX: 0,
  yLabelOffsetY: 50,
  yLabelRotation: 0,
  xLabelOffsetX: 0,
  xLabelOffsetY: -50,
  xLabelRotation: 90,
  barWidth: 10,
};

optionData.options16 = {
  childTextSize: 10,
  color: 'green',
  colorScale: 'red',
  diameter: 400,
  endAngle: Math.PI / 1.25,
  fillColor: 'blue',
  fontFamily: 'sans-seriff',
  fontWeight: 'normal',
  height: 600,
  hoverColor: 'blue',
  innerRadius: 180,
  interval: 2000,
  levels: 5, // maybe should be calculated from data
  linkColor: 'black',
  majorTickColor: 'black',
  majorTicks: 5,
  margin: {
    bottom: 30, left: 40, right: 20, top: 20,
  },
  maxColor: 'red', // maybe should be d3 color scale
  maxValue: 100, // maybe should be calculated from data
  minColor: 'blue',
  minorTickColor: 'black',
  minorTicks: 4,
  nodeRadius: 15,
  onHover: false,
  opacity: 0.75,
  outerRadius: 200,
  overlay: true,
  padding: 0.1,
  parentTextSize: 12,
  pointerColor: 'red',
  pointerWidth: 10,
  radius: 250,
  relativeNodeSize: false,
  showCategories: true,
  showLabels: true,
  sortBy: 'value',
  stack: false,
  startAngle: -Math.PI / 1.25,
  strokeColor: 'blue',
  textAnchor: 'middle',
  textColor: 'white',
  width: 900,
  xLabel: 'xLabel',
  yLabel: 'yLabel',
  xTickFrequency: 10,
  yTickFrequency: 10,
  xTickLength: 10,
  yTickLength: 10,
  xTickExtension: 0,
  yTickExtension: 100,
  xTickOpacity: 1,
  yTickOpacity: 0.55,
  xAxisColor: 'red',
  yAxisColor: 'blue',
  xAxisPosition: -1,
  yAxisPosition: 880,
  yLabelOffsetX: 0,
  yLabelOffsetY: 50,
  yLabelRotation: 0,
  xLabelOffsetX: 0,
  xLabelOffsetY: -50,
  xLabelRotation: 90,
  barWidth: 10,
};

optionData.options17 = {
  margin: {
    top: 20, right: 20, bottom: 30, left: 40,
  },
  width: 900,
  height: 800,
  opacity: 0.75,
  onHover: false,
  radius: 200,
  color: ['#1f77b4', '#ff7f0e', '#2ca02c', '#d62728', '#9467bd', '#8c564b', '#e377c2', '#7f7f7f', '#bcbd22', '#17becf'], // color scheme for the bars
  showLabels: true,
  diameter: 6,
  stack: false,
  // fillColor: ['red', 'blue', 'green', 'yellow', 'orange', 'purple'],
  fillColor: 'red',
  strokeColor: 'blue',
  xLabel: 'xLabel',
  yLabel: 'yLabel',

  colorScale: 'red',
  overlay: false,
  // colorScheme: d3.schemeCategory10,
  yLine: true,
  xLine: true,
  xTickFrequency: 10,
  yTickFrequency: 10,
  xTickLength: 10,
  yTickLength: 10,
  xTickExtension: 1,
  yTickExtension: 1,
  xTickOpacity: 1,
  yTickOpacity: 1,
  xAxisColor: 'red',
  yAxisColor: 'purple',
  xAxisOpacity: 1,
  yAxisOpacity: 1,
  xTickFontSize: 10,
  yTickFontSize: 10,
  xFontColor: 'red',
  yFontColor: 'blue',
  xFontWeight: 'bold',
  yFontWeight: 'bold',
  xFontFamily: 'gothic',
  yFontFamily: 'sans-serif',
  yLabelFontColor: 'red',
  xLabelFontColor: 'blue',
  yLabelFontWeight: 'bold',
  xLabelFontWeight: 'bold',
  yLabelFontFamily: 'gothic',
  xLabelFontFamily: 'sans-serif',
  yLabelFontSize: 10,
  // xLabelFontSize: 100,
  // xLabelOffsetx: 10,
  // xLabelOffsety: 10,
  xFontOpacity: 1,
  yFontOpacity: 1,
  xFontStyle: 'italic',
  yFontStyle: 'italic',
  xTextAnchor: 'start',
  xAxisPosition: -1,
  yAxisPosition: 880,
  yLabelOffsetX: 0,
  yLabelOffsetY: 50,
  yLabelRotation: 0,
  xLabelOffsetX: 0,
  xLabelOffsetY: -50,
  xLabelRotation: 90,
  barWidth: 10,
};

optionData.options18 = {
  margin: {
    top: 20, right: 20, bottom: 30, left: 40,
  },
  width: 1600,
  height: 900,
  radius: 50.5,
  color: d3.scaleOrdinal(d3.schemeCategory10),
  showCategories: true,
  diameter: 100,
  fillColor: ['red', 'blue', 'green', 'yellow', 'orange', 'purple'],
  overlay: true,
  opacity: 1,
  onHover: false,
  stack: false,
  textAnchor: 'middle',
  textColor: 'white',
  xLine: true,
  yLine: true,
  xLabel: 'xLabel',
  yLabel: 'yLabel',
  xTickFrequency: 10,
  yTickFrequency: 10,
  xTickLength: 10,
  yTickLength: 10,
  xTickExtension: 0,
  yTickExtension: 100,
  xTickOpacity: 1,
  yTickOpacity: 0.55,
  xAxisColor: 'red',
  yAxisColor: 'blue',
  xAxisPosition: -1,
  yAxisPosition: 880,
  yLabelOffsetX: 0,
  yLabelOffsetY: 50,
  yLabelRotation: 0,
  xLabelOffsetX: 0,
  xLabelOffsetY: -50,
  xLabelRotation: 90,
  barWidth: 10,
};
optionData.options19 = {
  childTextSize: 10,
  color: 'green',
  colorScale: 'blue',
  colorScheme: d3.schemeCategory10,
  diameter: 400,
  duration: 500,
  endAngle: Math.PI / 1.25,
  fillColor: 'red',
  fontFamily: 'sans-seriff',
  fontWeight: 'normal',
  gradient: true,
  gradientColor: ['purple', 'green'],
  gradientAxis: 'x',
  hoverColor: 'blue',
  innerRadius: 180,
  interval: 2000,
  levels: 5, // maybe should be calculated from data
  linkColor: 'black',
  majorTickColor: 'black',
  majorTicks: 5,
  margin: {
    top: 20, right: 20, bottom: 30, left: 40,
  },
  width: 900,
  height: 600,
  maxColor: 'red', // maybe should be d3 color scale
  maxValue: 100, // maybe should be calculated from data
  minColor: 'blue',
  minorTickColor: 'black',
  minorTicks: 4,
  nodeRadius: 5,
  // onHover: true,
  opacity: 1,
  outerRadius: 200,
  overlay: true,
  padding: 0.1,
  parentTextSize: 12,
  pointerColor: 'red',
  pointerWidth: 10,
  radius: 5,
  relativeNodeSize: false,
  showCategories: true,
  showLabels: true,
  sortBy: 'y asc',
  stack: false,
  startAngle: -Math.PI / 1.25,
  strokeColor: 'blue',
  textAnchor: 'middle',
  textColor: 'white',
  xLine: true,
  yLine: false,
  xLabel: 'xLabel',
  yLabel: 'yLabel',
  xTickFrequency: 10,
  yTickFrequency: 10,
  xTickLength: 10,
  yTickLength: 10,
  xTickExtension: 0,
  yTickExtension: 100,
  xTickOpacity: 1,
  yTickOpacity: 0.55,
  xAxisColor: 'red',
  yAxisColor: 'blue',
  xAxisPosition: -1,
  yAxisPosition: 880,
  yLabelOffsetX: 0,
  yLabelOffsetY: 50,
  yLabelRotation: 0,
  xLabelOffsetX: 0,
  xLabelOffsetY: -50,
  xLabelRotation: 90,
  barWidth: 10,
};
optionData.options20 = {
  width: 2800,
  height: 2600,
  maxRadius: 100,
  chargeStrength: 0.01,
  fontSize: (d) => Math.sqrt(d.value) * 2,
  bubble: true,
  bubbleOpacity: 0.7,
  y2ForceStrength: -0.01,
  xTickFrequency: 10,
  yTickFrequency: 10,
  xTickLength: 10,
  yTickLength: 10,
  xTickExtension: 0,
  yTickExtension: 100,
  xTickOpacity: 1,
  yTickOpacity: 0.55,
  xAxisColor: 'red',
  yAxisColor: 'blue',
  xAxisPosition: -1,
  yAxisPosition: 880,
  yLabelOffsetX: 0,
  yLabelOffsetY: 50,
  yLabelRotation: 0,
  xLabelOffsetX: 0,
  xLabelOffsetY: -50,
  xLabelRotation: 90,
  barWidth: 10,
};
