export default class D3OptionTypes {
  // TODO figure out a user input for colorscheme that doesnt involve d3 on the front end
  constructor() {
    const types = {
      optionsAdjacency: {
        _selfKey: 'optionsAdjacency',
        chartClass: 'string',
        chartNumber: 'number',
        height: 'number',
        minColor: 'string',
        margin: {
          bottom: 'number',
          left: 'number',
          right: 'number',
          top: 'number',
        },
        maxColor: 'string',
        width: 'number',
        xDomain: ['number'],
        xLabel: 'string',
        xLabelFontColor: 'string',
        xLabelFontFamily: 'string',
        xLabelFontSize: 'number',
        xLabelFontOpacity: 'number',
        xLabelFontWeight: 'string',
        xLabelOffsetX: 'number',
        xLabelOffsetY: 'number',
        xLabelRotation: 'number',
        xLine: 'boolean',
        xTickExtension: 'number',
        xTickFontColor: 'string',
        xTickFontFamily: 'string',
        xTickFontOpacity: 'number',
        xTickFontWeight: 'string',
        xTickFontSize: 'number',
        xTickFrequency: 'number',
        xTickLength: 'number',
        xTickOpacity: 'number',
        xAxisColor: 'string',
        xAxisPosition: 'number',
        yDomain: ['number'],
        yLabel: 'string',
        yLabelFontColor: 'string',
        yLabelFontFamily: 'string',
        yLabelFontSize: 'number',
        yLabelFontOpacity: 'number',
        yLabelFontWeight: 'string',
        yLabelOffsetX: 'number',
        yLabelOffsetY: 'number',
        yLabelRotation: 'number',
        yLine: 'boolean',
        yTickExtension: 'number',
        yTickFontColor: 'string',
        yTickFontFamily: 'string',
        yTickFontOpacity: 'number',
        yTickFontWeight: 'string',
        yTickFontSize: 'number',
        yTickFrequency: 'number',
        yTickLength: 'number',
        yAxisColor: 'string',
        yAxisPosition: 'number',
      },

      optionsChord: {
        _selfKey: 'optionsChord',
        chartClass: 'string',
        chartNumber: 'number',
        colorScheme: ['string'],
        childTextSize: 'number',
        height: 'number',
        innerRadius: 'number',
        margin: {
          bottom: 'number',
          left: 'number',
          right: 'number',
          top: 'number',
        },
        outerRadius: 'number',
        textAnchor: 'string',
        strokeColor: 'string',
        width: 'number',
      },

      optionsCloud: {
        _selfKey: 'optionsCloud',
        chartClass: 'string',
        chartNumber: 'number',
        colorScheme: ['string'],
        bubble: 'boolean',
        bubbleOpacity: 'number',
        chargeStrength: 'number',
        fontColor: 'string',
        height: 'number',
        margin: {
          bottom: 'number',
          left: 'number',
          right: 'number',
          top: 'number',
        },
        maxRadius: 'number',
        textAnchor: 'string',
        width: 'number',
        y2ForceStrength: 'number',
      },

      optionsCluster: {
        _selfKey: 'optionsCluster',
        chartClass: 'string',
        chartNumber: 'number',
        childTextSize: 'number',
        colorScheme: ['string'],
        height: 'number',
        margin: {
          bottom: 'number',
          left: 'number',
          right: 'number',
          top: 'number',
        },
        label: 'string',
        nodeRadius: 'number',
        strokeColor: 'string',
        strokeWidth: 'number',
        width: 'number',
      },

      optionsDendrogram: {
        _selfKey: 'optionsDendrogram',
        chartClass: 'string',
        chartNumber: 'number',
        childTextSize: 'number',
        fontColor: 'string',
        height: 'number',
        linkColor: 'string',
        margin: {
          bottom: 'number',
          left: 'number',
          right: 'number',
          top: 'number',
        },
        nodeColor: 'string',
        nodeRadius: 'number',
        strokeColor: 'string',
        width: 'number',
      },
      optionsIcicle: {
        _selfKey: 'optionsIcicle',
        chartClass: 'string',
        chartNumber: 'number',
        childTextSize: 'number',
        colorScheme: ['string'],
        height: 'number',
        label: 'string',
        margin: {
          bottom: 'number',
          left: 'number',
          right: 'number',
          top: 'number',
        },
        onHover: 'boolean',
        width: 'number',
      },

      optionsFunnel: {
        _selfKey: 'optionsFunnel',
        animate: 'boolean',
        boxShadow: 'boolean',
        chartClass: 'string',
        chartNumber: 'number',
        colorScheme: ['string', 'string'],
        // gradient: 'boolean',
        // gradientAxis: 'string',
        // gradientColor: ['string'],
        height: 'number',
        hoverColor: 'string',
        isUpdating: 'boolean',
        margin: {
          bottom: 'number',
          left: 'number',
          right: 'number',
          top: 'number',
        },
        onHover: 'boolean',
        padding: 'number',
        radius: 'number',
        strokeColor: 'string',
        width: 'number',
        xDomain: ['number'],
        xLabel: 'string',
        xLabelFontColor: 'string',
        xLabelFontFamily: 'string',
        xLabelFontSize: 'number',
        xLabelFontOpacity: 'number',
        xLabelFontWeight: 'string',
        xLabelOffsetX: 'number',
        xLabelOffsetY: 'number',
        xLabelRotation: 'number',
        xLine: 'boolean',
        xTickExtension: 'number',
        xTickFontColor: 'string',
        xTickFontFamily: 'string',
        xTickFontOpacity: 'number',
        xTickFontWeight: 'string',
        xTickFontSize: 'number',
        xTickFrequency: 'number',
        xTickLength: 'number',
        xTickOpacity: 'number',
        xAxisColor: 'string',
        xAxisPosition: 'number',
        yDomain: ['number'],
        yLabel: 'string',
        yLabelFontColor: 'string',
        yLabelFontFamily: 'string',
        yLabelFontSize: 'number',
        yLabelFontOpacity: 'number',
        yLabelFontWeight: 'string',
        yLabelOffsetX: 'number',
        yLabelOffsetY: 'number',
        yLabelRotation: 'number',
        yLine: 'boolean',
        yTickExtension: 'number',
        yTickFontColor: 'string',
        yTickFontFamily: 'string',
        yTickFontOpacity: 'number',
        yTickFontWeight: 'string',
        yTickFontSize: 'number',
        yTickFrequency: 'number',
        yTickLength: 'number',
        yAxisColor: 'string',
        yAxisPosition: 'number',
      },

      optionsGauge: {
        _selfKey: 'optionsGauge',
        chartClass: 'string',
        chartNumber: 'number',
        height: 'number',
        interval: 'number',
        majorTickColor: 'string',
        majorTicks: 'number',
        margin: {
          bottom: 'number',
          left: 'number',
          right: 'number',
          top: 'number',
        },
        minorTickColor: 'string',
        minorTicks: 'number',
        pointerColor: 'string',
        pointerWidth: 'number',
        startAngle: 'number',
        endAngle: 'number',
        width: 'number',
      },

      optionsHeat: {
        _selfKey: 'optionsHeat',
        chartClass: 'string',
        chartNumber: 'number',
        colorScheme: ['string'],
        height: 'number',
        hoverColor: 'string',
        margin: {
          bottom: 'number',
          left: 'number',
          right: 'number',
          top: 'number',
        },
        onHover: 'boolean',
        width: 'number',
        textAnchor: 'string',
        xLabel: 'string',
        xAxisColor: 'string',
        xAxisPosition: 'number',
        xLabelOffsetX: 'number',
        xLabelOffsetY: 'number',
        xLabelRotation: 'number',
        xTickFontColor: 'string',
        xTickFontFamily: 'string',
        xTickFontOpacity: 'number',
        xTickFontWeight: 'string',
        xTickFontSize: 'number',
        xTickExtension: 'number',
        xTickFrequency: 'number',
        xTickLength: 'number',
        xTickOpacity: 'number',
        yLabel: 'string',
        yTickFontColor: 'string',
        yTickFontFamily: 'string',
        yTickFontOpacity: 'number',
        yTickFontWeight: 'string',
        yTickFontSize: 'number',
        yTickExtension: 'number',
        yTickFrequency: 'number',
        yTickLength: 'number',
        yTickOpacity: 'number',
        yAxisColor: 'string',
        yAxisPosition: 'number',
        yLabelOffsetX: 'number',
        yLabelOffsetY: 'number',
        yLabelRotation: 'number',
      },

      options1: {
        _selfKey: 'options1',
        barWidth: -30,
        childTextSize: 10,
        color: 'red',
        colorScheme: ['red', 'blue', 'green'],
        diameter: 600,
        // endAngle: Math.PI / 1.25,
        fillColor: 'blue',
        // fontFamily: 'sans-seriff',
        // fontWeight: 'normal',
        // gradient: true,
        gradientAxis: 'x',
        gradientColor: ['red', 'yellow'],
        height: 600,
        hoverColor: 'blue',
        innerRadius: 180,
        // interval: 2000,
        // levels: 5, // maybe should be calculated from data
        // linkColor: 'black',
        // majorTickColor: 'black',
        // majorTicks: 5,
        margin: {
          bottom: 30, left: 40, right: 20, top: 20,
        },
        // maxColor: 'red', // maybe should be d3 color scale
        // maxValue: 100, // maybe should be calculated from data
        // minColor: 'blue',
        // minorTickColor: 'black',
        // minorTicks: 4,
        // nodeRadius: 15,
        onHover: false,
        opacity: 1,
        outerRadius: 200,
        // padding: 0.1,
        // parentTextSize: 12,
        // pointerColor: 'red',
        // pointerWidth: 10,
        radius: 100,
        // sortBy: 'value',
        // stack: true,
        // startAngle: -Math.PI / 1.25,
        // strokeColor: 'blue',
        // textAnchor: 'middle',
        // textColor: 'white',
        width: 900,
        xLabel: 'xLabel',
        // xLabelColor: 'red',
        xLabelFontSize: 10,
        xLabelFontFamily: 'sans-serif',
        xLabelFontWeight: 'normal',
        xLabelOffsetX: 10,
        xLabelOffsetY: 10,
        xLabelRotation: 0,
        xLine: true,
        xTickExtension: 1,
        xTickFrequency: 10,
        xTickLength: 10,
        xTickOpacity: 0.21,
        xAxisColor: 'red',
        xAxisPosition: -1,
        yLabel: 'yLabel',
        // yLabelColor: 'blue',
        yLabelFontSize: 10,
        yLabelFontFamily: 'sans-serif',
        yLabelFontWeight: 'normal',
        yLabelOffsetX: 10,
        yLabelOffsetY: 50,
        yLabelRotation: 0,
        yLine: true,
        yTickExtension: 1,
        yTickFrequency: 10,
        yTickLength: 10,
        yTickOpacity: 0.1,
        yAxisColor: 'blue',
        yAxisPosition: 880,
      },
      optionsArea: {
        _selfKey: 'optionsArea',
        chartClass: 'string',
        chartNumber: 'number',
        animate: 'boolean',
        boxShadow: 'boolean',
        fillColor: 'string',
        gradient: 'boolean',
        gradientAxis: 'string',
        gradientColor: ['string'],
        height: 'number',
        hoverColor: 'string',
        isUpdating: 'boolean',
        margin: {
          top: 'number',
          bottom: 'number',
          left: 'number',
          right: 'number',
        },
        onHover: 'boolean',
        opacity: 'number',
        sortBy: 'string',
        // stack: 'boolean',
        textAnchor: 'string',
        width: 'number',
        xDomain: ['number'],
        xLabel: 'string',
        xLabelFontColor: 'string',
        xLabelFontFamily: 'string',
        xLabelFontSize: 'number',
        xLabelFontOpacity: 'number',
        xLabelFontWeight: 'string',
        xLabelOffsetX: 'number',
        xLabelOffsetY: 'number',
        xLabelRotation: 'number',
        xLine: 'boolean',
        xTickExtension: 'number',
        xTickFontColor: 'string',
        xTickFontFamily: 'string',
        xTickFontOpacity: 'number',
        xTickFontWeight: 'string',
        xTickFontSize: 'number',
        xTickFrequency: 'number',
        xTickLength: 'number',
        xTickOpacity: 'number',
        xAxisColor: 'string',
        xAxisPosition: 'number',
        yDomain: ['number'],
        yLabel: 'string',
        yLabelFontColor: 'string',
        yLabelFontFamily: 'string',
        yLabelFontSize: 'number',
        yLabelFontOpacity: 'number',
        yLabelFontWeight: 'string',
        yLabelOffsetX: 'number',
        yLabelOffsetY: 'number',
        yLabelRotation: 'number',
        yLine: 'boolean',
        yTickExtension: 'number',
        yTickFontColor: 'string',
        yTickFontFamily: 'string',
        yTickFontOpacity: 'number',
        yTickFontWeight: 'string',
        yTickFontSize: 'number',
        yTickFrequency: 'number',
        yTickLength: 'number',
        yAxisColor: 'string',
        yAxisPosition: 'number',
      },

      optionsBox: {
        _selfKey: 'optionsBox',
        chartClass: 'string',
        chartNumber: 'number',
        // animate: 'boolean',
        boxShadow: 'boolean',
        boxWidth: 'number',
        fillColor: 'string',
        gradient: 'boolean',
        gradientAxis: 'string',
        gradientColor: ['string'],
        height: 'number',
        hoverColor: 'string',
        isUpdating: 'boolean',
        margin: {
          top: 'number',
          bottom: 'number',
          left: 'number',
          right: 'number',
        },
        onHover: 'boolean',
        opacity: 'number',
        sortBy: 'string',
        strokeColor: 'string',
        // stack: 'boolean',
        textAnchor: 'string',
        width: 'number',
        xDomain: ['number'],
        xLabel: 'string',
        xLabelFontColor: 'string',
        xLabelFontFamily: 'string',
        xLabelFontSize: 'number',
        xLabelFontOpacity: 'number',
        xLabelFontWeight: 'string',
        xLabelOffsetX: 'number',
        xLabelOffsetY: 'number',
        xLabelRotation: 'number',
        xLine: 'boolean',
        xTickExtension: 'number',
        xTickFontColor: 'string',
        xTickFontFamily: 'string',
        xTickFontOpacity: 'number',
        xTickFontWeight: 'string',
        xTickFontSize: 'number',
        xTickFrequency: 'number',
        xTickLength: 'number',
        xTickOpacity: 'number',
        xAxisColor: 'string',
        xAxisPosition: 'number',
        yDomain: ['number'],
        yLabel: 'string',
        yLabelFontColor: 'string',
        yLabelFontFamily: 'string',
        yLabelFontSize: 'number',
        yLabelFontOpacity: 'number',
        yLabelFontWeight: 'string',
        yLabelOffsetX: 'number',
        yLabelOffsetY: 'number',
        yLabelRotation: 'number',
        yLine: 'boolean',
        yTickExtension: 'number',
        yTickFontColor: 'string',
        yTickFontFamily: 'string',
        yTickFontOpacity: 'number',
        yTickFontWeight: 'string',
        yTickFontSize: 'number',
        yTickFrequency: 'number',
        yTickLength: 'number',
        yAxisColor: 'string',
        yAxisPosition: 'number',
      },

      optionsDonut: {
        _selfKey: 'optionsDonut',
        chartClass: 'string',
        chartNumber: 'number',
        colorScheme: ['string'],
        fontSize: 'number',
        height: 'number',
        hoverColor: 'string',
        innerRadius: 'number',
        margin: {
          bottom: 'number',
          left: 'number',
          right: 'number',
          top: 'number',
        },
        onHover: 'boolean',
        opacity: 'number',
        outerRadius: 'number',
        // stack: 'boolean',
        strokeColor: 'string',
        strokeWidth: 'number',
        textAnchor: 'string',
        width: 'number',
      },

      optionsBar: {
        _selfKey: 'optionsBar',
        chartClass: 'string',
        chartNumber: 'number',
        animate: 'boolean',
        barWidth: 'number',
        boxShadow: 'boolean',
        fillColor: 'string',
        gradient: 'boolean',
        gradientAxis: 'string',
        gradientColor: ['string'],
        height: 'number',
        hoverColor: 'string',
        isUpdating: 'boolean',
        margin: {
          top: 'number',
          bottom: 'number',
          left: 'number',
          right: 'number',
        },
        onHover: 'boolean',
        opacity: 'number',
        sortBy: 'string',
        // stack: 'boolean',
        strokeColor: 'string',
        strokeWidth: 'number',
        textAnchor: 'string',
        width: 'number',
        xDomain: ['number'],
        xLabel: 'string',
        xLabelFontColor: 'string',
        xLabelFontFamily: 'string',
        xLabelFontSize: 'number',
        xLabelFontOpacity: 'number',
        xLabelFontWeight: 'string',
        xLabelOffsetX: 'number',
        xLabelOffsetY: 'number',
        xLabelRotation: 'number',
        xLine: 'boolean',
        xTickExtension: 'number',
        xTickFontColor: 'string',
        xTickFontFamily: 'string',
        xTickFontOpacity: 'number',
        xTickFontWeight: 'string',
        xTickFontSize: 'number',
        xTickFrequency: 'number',
        xTickLength: 'number',
        xTickOpacity: 'number',
        xAxisColor: 'string',
        xAxisPosition: 'number',
        yDomain: ['number'],
        yLabel: 'string',
        yLabelFontColor: 'string',
        yLabelFontFamily: 'string',
        yLabelFontSize: 'number',
        yLabelFontOpacity: 'number',
        yLabelFontWeight: 'string',
        yLabelOffsetX: 'number',
        yLabelOffsetY: 'number',
        yLabelRotation: 'number',
        yLine: 'boolean',
        yTickExtension: 'number',
        yTickFontColor: 'string',
        yTickFontFamily: 'string',
        yTickFontOpacity: 'number',
        yTickFontWeight: 'string',
        yTickFontSize: 'number',
        yTickFrequency: 'number',
        yTickLength: 'number',
        yAxisColor: 'string',
        yAxisPosition: 'number',
      },

      optionsPie: {
        _selfKey: 'optionsPie',
        animate: 'boolean',
        chartClass: 'string',
        chartNumber: 'number',
        colorScheme: ['string'],
        fontColor: 'string',
        fontFamily: 'string',
        fontOpacity: 'number',
        fontWeight: 'string',
        fontSize: 'number',
        height: 'number',
        hoverColor: 'string',
        innerRadius: 'number',
        interval: 'number',
        isUpdating: 'boolean',
        margin: {
          bottom: 'number',
          left: 'number',
          right: 'number',
          top: 'number',
        },
        onHover: 'boolean',
        opacity: 'number',
        outerRadius: 'number',
        // padding: 'number',
        parentTextSize: 'number',
        // pointerColor: 'string',
        // pointerWidth: 'number',
        radius: 'number',
        showCategories: 'boolean',
        // sortBy: 'string',
        // stack: 'boolean',
        strokeColor: 'string',
        strokeWidth: 'number',
        textAnchor: 'string',
        textColor: 'string',
        width: 'number',
        xLabelFontSize: 'number',
      },

      // optionsStacked: {
      //   _selfKey: 'optionsStacked',
      //   colorScheme: ['red', 'blue', 'yellow'],
      //   height: 800,
      //   margin: {
      //     bottom: 30, left: 40, right: 20, top: 20,
      //   },
      //   onHover: false,
      //   opacity: 0.75,
      //   // stack: false,
      //   width: 900,
      //   xLabel: 'xLabel',
      //   // xFontColor: 'red',
      //   // xFontFamily: 'gothic',
      //   // xFontOpacity: 1,
      //   // xFontWeight: 'bold',
      //   xLabelFontColor: 'blue',
      //   xLabelFontFamily: 'sans-serif',
      //   xLabelFontWeight: 'bold',
      //   xLabelOffsetX: 0,
      //   xLabelOffsetY: -50,
      //   xLabelRotation: 90,
      //   xLine: true,
      //   xAxisColor: 'red',
      //   xAxisOpacity: 1,
      //   xAxisPosition: -1,
      //   xDomain: ['number'],
      //   // xTextAnchor: 'start',
      //   xTickExtension: 1,
      //   xTickFrequency: 10,
      //   xTickLength: 10,
      //   // yFontColor: 'blue',
      //   // yFontFamily: 'sans-serif',
      //   // yFontOpacity: 1,
      //   // yFontWeight: 'bold',
      //   yLabel: 'yLabel',
      //   yLabelFontColor: 'red',
      //   yLabelFontFamily: 'gothic',
      //   yLabelFontWeight: 'bold',
      //   yLabelOffsetX: 0,
      //   yLabelOffsetY: 50,
      //   yLabelRotation: 0,
      //   yLine: true,
      //   yAxisColor: 'purple',
      //   // yAxisOpacity: 1,
      //   yAxisPosition: 880,
      //   yTickExtension: 1,
      //   yTickFrequency: 10,
      //   yTickLength: 10,
      //   yTickOpacity: 1,
      // },
      optionsStacked: {
        _selfKey: 'optionsStacked',
        chartClass: 'string',
        chartNumber: 'number',
        colorScheme: ['string'],
        height: 'number',
        margin: {
          bottom: 'number',
          left: 'number',
          right: 'number',
          top: 'number',
        },
        onHover: 'boolean',
        opacity: 'number',
        width: 'number',
        xAxisColor: 'string',
        xAxisOpacity: 'number',
        xAxisPosition: 'number',
        xAxisTickOpacity: 'number',
        xDomain: ['number'],
        xLabel: 'string',
        xLabelFontColor: 'string',
        xLabelFontFamily: 'string',
        xLabelFontWeight: 'string',
        xLabelFontOpacity: 'number',
        xLabelFontSize: 'number',
        xLabelOffsetX: 'number',
        xLabelOffsetY: 'number',
        xLabelRotation: 'number',
        xLine: 'boolean',
        yDomain: ['number'],
        xTickExtension: 'number',
        xTickOpacity: 'number',
        xTickFontColor: 'string',
        xTickFontFamily: 'string',
        xTickFontOpacity: 'number',
        xTickFontWeight: 'string',
        xTickFontSize: 'number',
        xTickFrequency: 'number',
        xTickLength: 'number',
        yAxisColor: 'string',
        yAxisPosition: 'number',
        yAxisOpacity: 'number',
        yAxisTickOpacity: 'number',
        yLabel: 'string',
        yLabelFontColor: 'string',
        yLabelFontFamily: 'string',
        yLabelFontOpacity: 'number',
        yLabelFontSize: 'number',
        yLabelFontWeight: 'string',
        yLabelOffsetX: 'number',
        yLabelOffsetY: 'number',
        yLabelRotation: 'number',
        yLine: 'boolean',
        yTickExtension: 'number',
        yTickOpacity: 'number',
        yTickFrequency: 'number',
        yTickFontColor: 'string',
        yTickFontFamily: 'string',
        yTickFontOpacity: 'number',
        yTickFontWeight: 'string',
        yTickFontSize: 'number',
        yTickLength: 'number',
      },

      optionsLine: {
        _selfKey: 'optionsLine',
        animate: 'boolean',
        chartClass: 'string',
        chartNumber: 'number',
        boxShadow: 'boolean',
        gradient: 'boolean',
        gradientAxis: 'string',
        gradientColor: ['string'],
        height: 'number',
        hoverColor: 'string',
        isUpdating: 'boolean',
        margin: {
          top: 'number',
          bottom: 'number',
          left: 'number',
          right: 'number',
        },
        onHover: 'boolean',
        opacity: 'number',
        sortBy: 'string',
        strokeColor: 'string',
        strokeWidth: 'number',
        width: 'number',
        xDomain: ['number'],
        xLabel: 'string',
        xLabelFontColor: 'string',
        xLabelFontFamily: 'string',
        xLabelFontSize: 'number',
        xLabelFontOpacity: 'number',
        xLabelFontWeight: 'string',
        xLabelOffsetX: 'number',
        xLabelOffsetY: 'number',
        xLabelRotation: 'number',
        xLine: 'boolean',
        xTickExtension: 'number',
        xTickFontColor: 'string',
        xTickFontFamily: 'string',
        xTickFontOpacity: 'number',
        xTickFontWeight: 'string',
        xTickFontSize: 'number',
        xTickFrequency: 'number',
        xTickLength: 'number',
        xTickOpacity: 'number',
        xAxisColor: 'string',
        xAxisPosition: 'number',
        yDomain: ['number'],
        yLabel: 'string',
        yLabelFontColor: 'string',
        yLabelFontFamily: 'string',
        yLabelFontSize: 'number',
        yLabelFontOpacity: 'number',
        yLabelFontWeight: 'string',
        yLabelOffsetX: 'number',
        yLabelOffsetY: 'number',
        yLabelRotation: 'number',
        yLine: 'boolean',
        yTickExtension: 'number',
        yTickFontColor: 'string',
        yTickFontFamily: 'string',
        yTickFontOpacity: 'number',
        yTickFontWeight: 'string',
        yTickFontSize: 'number',
        yTickFrequency: 'number',
        yTickLength: 'number',
        yAxisColor: 'string',
        yAxisPosition: 'number',
      },

      optionsBubble: {
        _selfKey: 'optionsBubble',
        chartClass: 'string',
        chartNumber: 'number',
        opacity: 'number',
        childTextSize: 'number',
        colorScheme: ['string'],
        diameter: 'number',
        fontColor: 'string',
        height: 'number',
        label: 'string',
        maxRadius: 'number',
        padding: 'number',
        parentTextSize: 'number',
        textAnchor: 'string',
        width: 'number',
      },

      optionsMarimekko: {
        _selfKey: 'optionsMarimekko',
        chartClass: 'string',
        chartNumber: 'number',
        colorScheme: ['string'],
        height: 'number',
        margin: {
          bottom: 'number',
          left: 'number',
          right: 'number',
          top: 'number',
        },
        width: 'number',
        xDomain: ['number'],
        xLabel: 'string',
        xLabelFontColor: 'string',
        xLabelFontFamily: 'string',
        xLabelFontSize: 'number',
        xLabelFontOpacity: 'number',
        xLabelFontWeight: 'string',
        xLabelOffsetX: 'number',
        xLabelOffsetY: 'number',
        xLabelRotation: 'number',
        xLine: 'boolean',
        xTickExtension: 'number',
        xTickFontColor: 'string',
        xTickFontFamily: 'string',
        xTickFontOpacity: 'number',
        xTickFontWeight: 'string',
        xTickFontSize: 'number',
        xTickFrequency: 'number',
        xTickLength: 'number',
        xTickOpacity: 'number',
        xAxisColor: 'string',
        xAxisPosition: 'number',
        yDomain: ['string'],
        yLabel: 'string',
        yLabelFontColor: 'string',
        yLabelFontFamily: 'string',
        yLabelFontSize: 'number',
        yLabelFontOpacity: 'number',
        yLabelFontWeight: 'string',
        yLabelOffsetX: 'number',
        yLabelOffsetY: 'number',
        yLabelRotation: 'number',
        yLine: 'boolean',
        yTickExtension: 'number',
        yTickFontColor: 'string',
        yTickFontFamily: 'string',
        yTickFontOpacity: 'number',
        yTickFontWeight: 'string',
        yTickFontSize: 'number',
        yTickFrequency: 'number',
        yTickLength: 'number',
        yAxisColor: 'string',
        yAxisPosition: 'number',
      },

      optionsPolar: {
        _selfKey: 'optionsPolar',
        chartClass: 'string',
        chartNumber: 'number',
        colorScheme: ['string'],
        fontColor: 'string',
        fontOpacity: 'number',
        fontSize: 'number',
        fontWeight: 'string',
        height: 'number',
        hoverColor: 'string',
        innerRadius: 'number',
        margin: {
          bottom: 'number',
          left: 'number',
          right: 'number',
          top: 'number',
        },
        opacity: 'number',
        onHover: 'boolean',
        outerRadius: 'number',
        showCategories: 'boolean',
        textAnchor: 'string',
        width: 'number',
      },
      optionsRadar: {
        _selfKey: 'optionsRadar',
        chartClass: 'string',
        chartNumber: 'number',
        // barWidth: 'number',
        colorScheme: ['string'],
        fontColor: 'string',
        fontSize: 'number',
        height: 'number',
        levels: 'number',
        margin: {
          bottom: 'number',
          left: 'number',
          right: 'number',
          top: 'number',
        },
        maxValue: 'number',
        width: 'number',
        showCategories: 'boolean',
        strokeColor: 'string',
        strokeWidth: 'number',
        textAnchor: 'string',
        xLabelFontSize: 'number',
      },

      optionsRadialTree: {
        _selfKey: 'optionsRadialTree',
        angle: 'number',
        chartClass: 'string',
        chartNumber: 'number',
        childTextSize: 'number',
        fillColor: 'string',
        fontColor: 'string',
        fontFamily: 'string',
        fontWeight: 'string',
        height: 'number',
        radius: 'number',
        linkColor: 'string',
        nodeRadius: 'number',
        nodeColor: 'string',
        width: 'number',
      },

      optionsSankey: {
        _selfKey: 'optionsSankey',
        chartClass: 'string',
        chartNumber: 'number',
        childTextSize: 'number',
        colorScheme: ['string'],
        fontColor: 'string',
        height: 'number',
        margin: {
          bottom: 'number',
          left: 'number',
          right: 'number',
          top: 'number',
        },
        radius: 'number',
        nodePadding: 'number',
        nodeRadius: 'number',
        nodeColor: 'string',
        strokeColor: 'string',
        textAnchor: 'string',
        width: 'number',
      },

      optionsSun: {
        _selfKey: 'optionsSun',
        chartClass: 'string',
        chartNumber: 'number',
        childTextSize: 'number',
        colorScheme: ['string'],
        label: 'string',
        height: 'number',
        radius: 'number',
        width: 'number',
      },

      optionsScatter: {
        _selfKey: 'optionsScatter',
        animate: 'boolean',
        color: 'string',
        chartClass: 'string',
        chartNumber: 'number',
        boxShadow: 'boolean',
        gradient: 'boolean',
        gradientAxis: 'string',
        gradientColor: ['string'],
        height: 'number',
        hoverColor: 'string',
        isUpdating: 'boolean',
        margin: {
          top: 'number',
          bottom: 'number',
          left: 'number',
          right: 'number',
        },
        minNodeSize: 'number',
        maxNodeSize: 'number',
        nodeRadius: 'number',
        onHover: 'boolean',
        opacity: 'number',
        relativeNode: 'boolean',
        sortBy: 'string',
        width: 'number',
        xDomain: ['number'],
        xLabel: 'string',
        xLabelFontColor: 'string',
        xLabelFontFamily: 'string',
        xLabelFontSize: 'number',
        xLabelFontOpacity: 'number',
        xLabelFontWeight: 'string',
        xLabelOffsetX: 'number',
        xLabelOffsetY: 'number',
        xLabelRotation: 'number',
        xLine: 'boolean',
        xTickExtension: 'number',
        xTickFontColor: 'string',
        xTickFontFamily: 'string',
        xTickFontOpacity: 'number',
        xTickFontWeight: 'string',
        xTickFontSize: 'number',
        xTickFrequency: 'number',
        xTickLength: 'number',
        xTickOpacity: 'number',
        xAxisColor: 'string',
        xAxisPosition: 'number',
        yDomain: ['number'],
        yLabel: 'string',
        yLabelFontColor: 'string',
        yLabelFontFamily: 'string',
        yLabelFontSize: 'number',
        yLabelFontOpacity: 'number',
        yLabelFontWeight: 'string',
        yLabelOffsetX: 'number',
        yLabelOffsetY: 'number',
        yLabelRotation: 'number',
        yLine: 'boolean',
        yTickExtension: 'number',
        yTickFontColor: 'string',
        yTickFontFamily: 'string',
        yTickFontOpacity: 'number',
        yTickFontWeight: 'string',
        yTickFontSize: 'number',
        yTickFrequency: 'number',
        yTickLength: 'number',
        yAxisColor: 'string',
        yAxisPosition: 'number',
      },

      optionsTreeDiagram: {
        _selfKey: 'optionsTreeDiagram',
        chartClass: 'string',
        chartNumber: 'number',
        childTextSize: 'number',
        color: 'string',
        fontColor: 'string',
        height: 'number',
        margin: {
          bottom: 'number',
          left: 'number',
          right: 'number',
          top: 'number',
        },
        radius: 'number',
        nodePadding: 'number',
        nodeRadius: 'number',
        nodeColor: 'string',
        opacity: 'number',
        strokeColor: 'string',
        strokeWidth: 'number',
        width: 'number',
      },
      optionsTreeMap: {
        _selfKey: 'optionsTreeMap',
        chartClass: 'string',
        chartNumber: 'number',
        childTextSize: 'number',
        colorScheme: ['string'],
        height: 'number',
        radius: 'number',
        opacity: 'number',
        width: 'number',
      },
      optionsVoronoi: {
        _selfKey: 'optionsVoronoi',
        chartClass: 'string',
        chartNumber: 'number',
        childTextSize: 'number',
        colorScheme: ['string'],
        height: 'number',
        radius: 'number',
        opacity: 'number',
        parentTextSize: 'number',
        strokeWidth: 'number',
        strokeColor: 'string',
        textAnchor: 'string',
        width: 'number',
      },

      optionsWaterfall: {
        _selfKey: 'optionsWaterfall',
        chartClass: 'string',
        chartNumber: 'number',
        barWidth: 'number',
        color: 'string',
        height: 'number',
        margin: {
          bottom: 'number',
          left: 'number',
          right: 'number',
          top: 'number',
        },
        width: 'number',
        xAxisColor: 'string',
        xAxisPosition: 'number',
        xDomain: ['number'],
        xLabel: 'string',
        xLabelFontColor: 'string',
        xLabelFontFamily: 'string',
        xLabelFontSize: 'number',
        xLabelFontOpacity: 'number',
        xLabelFontWeight: 'string',
        xLabelOffsetX: 'number',
        xLabelOffsetY: 'number',
        xLabelRotation: 'number',
        xLine: 'boolean',
        xTickExtension: 'number',
        xTickFontColor: 'string',
        xTickFontFamily: 'string',
        xTickFontOpacity: 'number',
        xTickFontWeight: 'string',
        xTickFontSize: 'number',
        xTickFrequency: 'number',
        xTickLength: 'number',
        xTickOpacity: 'number',
        yDomain: ['number'],
        yLabel: 'string',
        yLabelFontColor: 'string',
        yLabelFontFamily: 'string',
        yLabelFontSize: 'number',
        yLabelFontOpacity: 'number',
        yLabelFontWeight: 'string',
        yLabelOffsetX: 'number',
        yLabelOffsetY: 'number',
        yLabelRotation: 'number',
        yLine: 'boolean',
        yTickExtension: 'number',
        yTickFontColor: 'string',
        yTickFontFamily: 'string',
        yTickFontOpacity: 'number',
        yTickFontWeight: 'string',
        yTickFontSize: 'number',
        yTickFrequency: 'number',
        yTickLength: 'number',
        yAxisColor: 'string',
        yAxisPosition: 'number',
      },

    };

    Object.assign(this, types);
  }
}
